"""A paper trial that settles itself, so "is the edge real" stops being a guess.

`backtest.py` has always been ready to answer that question and has never had an input
file. The Kalshi half of that is now fixed (`settle.py`), but the only healthy flow this
project has is the whale board - and board tickets are Polymarket markets, which
`settle.py` does not and should not know about. This module is the missing half: it
takes each published ticket, holds it, and labels it when the market resolves.

WHY IT LIVES IN ``docs/``: the board is regenerated by a GitHub Action on a fresh
checkout every ~15 minutes, and `.gitignore` excludes `data/` and `*.jsonl`, so a trial
kept there would be erased on every run. Writing to `docs/trial.json` - which the
workflow already commits - means the trial accrues automatically from a job that
already exists, and every position lands in the public commit log at the moment it was
opened. That last part is the real prize: the standard objection to a paper record is
that it could have been written after the fact, and a git history on a public repo is
the cheapest possible answer to it.

DELIBERATELY FLAT STAKES. Tickets are recorded at a fixed notional rather than at the
board's conviction-weighted size, because those are two different hypotheses - "the
signal picks winners" and "the conviction score sizes them well" - and you cannot test
two hypotheses with zero data. Test the signal first; conviction is recorded on every
row so it can be sliced later, once there is something to slice.

``pred`` IS THE ENTRY PRICE, not a forecast of our own. The board is a copy-trade
signal: it claims a position is worth taking, never that P(win) is some number. So the
honest null is the market's own price, which makes `backtest`'s ``calibration_gap``
(avg_pred - win_rate) read directly as realised edge in probability points, with a
NEGATIVE gap meaning the tickets beat the price they were bought at.

MAKER-FIRST ENTRIES (``Config.maker_first``). Kalshi charges resting orders nothing
on standard markets while the taker fee peaks at 1.75c/contract - on a 1-3c gross
edge that is the biggest single EV lever the system has, so the trial simulates it
rather than assume it. A ticket that carries a ``bid`` becomes a PENDING order at
that bid instead of an instant taker fill at the ask; on each later poll it fills
only if the market's ask has come to the limit, and after ``maker_max_polls`` it
cancels into an expired-intent log (or, opt-in, crosses at the then-current ask at
taker fees). The log keeps fair value and edge AS OF INTENT TIME, because scoring
fills alone drops the unfilled winners and keeps the filled losers - adverse
selection dressed up as edge. Tickets without a bid (whale, probe, bridge) take the
ask, and are charged for it.

THE MAKER DISCOUNT IS EARNED, NEVER ASSUMED (corrected 2026-08-17). Everything that
is not a maker-first fill is a taker cross by construction: `signals.py` prices YES
at ``best_ask`` and NO at ``1 - best_bid``, so a ticket entered at those prices has
lifted the offer. The trial nevertheless booked those fills at a ``Config.assume_maker``
flag - 25% of the taker fee - for the whole of its first sample. The flag was deleted
outright on 2026-08-17 rather than pinned off, because a switch whose default is the
wrong answer is the shape of thing someone re-wires later. 287 of the 376 settled
rows in the headline population were charged that way, and not one of them carries
`fill_polls` or `maker`, which is the only evidence a resting order leaves; the three
rows in the file that do carry it are retired weather rows that really did rest.
Two changes follow from that, and they are deliberately different in kind:

  - FORWARD, `record` charges the taker fee on every instant fill. The maker branch
    survives only where a fill was OBSERVED (`_open_from_pending`).
  - BACKWARD, nothing is rewritten. `stats` scores a corrected COPY of each row -
    ``realized + fee_recorded - fee_correct`` - and publishes the as-recorded figures
    beside it under ``as_recorded``. The rows themselves keep the numbers they were
    written with, because the one thing this record has that a spreadsheet does not
    is that every row was committed once, at open time, and never touched again.
"""

from __future__ import annotations

import argparse
import json
import time
from collections import Counter
from collections.abc import Callable
from pathlib import Path

from . import sizing
from .bridge import is_derivative_title
from .copytrade import is_esports
from .fees import (
    DEFAULT_FEE_MULTIPLIER,
    INDEX_FEE_MULTIPLIER,
    is_designated,
    maker_trade_fee,
    trade_fee,
)

# A resolved Polymarket market pays its winning leg at 1 and the rest at 0. Demanding
# the extremes - rather than trusting `closed` alone - is what keeps a UMA dispute or a
# mid-resolution read from being labelled as a settled bet. Anything in between stays
# open and is retried next run; an unsettleable position must never become a data point.
WON_AT = 0.99
LOST_AT = 0.01

DEFAULT_STAKE = 100.0

# The model sleeves' own inputs, carried verbatim onto the row when the ticket has
# them. Without these the trial can prove a sleeve wins or loses but never WHY -
# `model_prob` against `won` is the calibration check each sleeve exists to earn, and
# a trial that drops it can validate the picks while leaving the model unfalsifiable.
# Weather fields (`*_f`), gas fields (aaa_*, drift, sigma, forecast, lr_tilt,
# market_mu, market_sigma) and spxindex fields (spot_used, chain_ts, vrp_shrink,
# fair, implied_sigma, series) never collide, so one spread list serves all: rows
# only pick up keys the ticket carries.
MODEL_FIELDS = ("model_prob", "edge", "forecast_f", "sigma_f", "market_mu_f",
                "market_sigma_f", "days_ahead", "market_prob", "model", "city",
                "forecast_src", "nbm_cycle", "nbm_sd_f", "forecast_grid_f",
                # Calibration-overlay verdict (calibration.py): the corrected market
                # probability, the edge against it, and the slope used. Carried so the
                # veto rule itself can be scored once rows settle.
                "cal_prob", "cal_edge", "cal_b",
                # Sports de-vig A/B: fair value under every method plus which one
                # was operative, so the trial can score multiplicative vs power vs
                # Shin from ONE run instead of needing a trial per method.
                "fair_mult", "fair_power", "fair_shin", "devig_method",
                "aaa_today", "aaa_target_date", "drift", "sigma", "forecast",
                "lr_tilt", "market_mu", "market_sigma",
                "spot_used", "chain_ts", "vrp_shrink", "fair", "implied_sigma",
                "series")

# The copy signal's OWN inputs, carried the same way and for the same reason. Both were
# computed and then dropped: across 583 rows the record holds zero wallet addresses and
# zero signal ages, which leaves "a good wallet bought this" - the entire thesis of the
# whale sleeve - permanently unauditable. `minutes_ago` is how stale the whale's fill
# already was when we copied it, and it is 15% of the conviction score; `wallet_usd` is
# who bought and for how much, which is what `n_wallets` and `whale_usd` are summaries
# of and what every concentration and bankroll rule is computed from.
#
# ADDRESSES IN PLAINTEXT, on purpose. They are already public on Polygon and on
# Polymarket's own leaderboard, so a hash protects nobody; what it would destroy is the
# join back to that leaderboard, which is the only reason to keep the address at all -
# "did the wallets we copied stay profitable" is unanswerable without it.
#
# Forward-only, like every other field here: a row is written once and never edited, so
# existing rows keep the shape they were committed with rather than being retro-filled.
SIGNAL_FIELDS = ("minutes_ago", "wallet_usd")


def venue_of(row: dict) -> str:
    """Which exchange a position lives on, inferred when the row predates the field.

    Rows written before Kalshi existed in the trial carry no ``venue``, and there are
    live ones in `docs/trial.json` - so this must keep working rather than relabel
    history. The id shape is unambiguous: Polymarket keys are `0x` + 64 hex, Kalshi
    tickers are uppercase series-and-strike. Defaulting to polymarket also means a
    corrupt or empty id keeps its old behaviour instead of being routed somewhere new.
    """
    v = (row.get("venue") or "").strip().lower()
    if v:
        return v
    mid = (row.get("market_id") or "").strip()
    # Note the shape of the test: an id must be PRESENT and non-Polymarket to route to
    # Kalshi. Asking only "does it lack an 0x prefix" sends an empty or corrupt id to
    # the new venue, which is the one case that should keep its old behaviour.
    return "kalshi" if mid and not mid.startswith("0x") else "polymarket"


def _key(market_id: str, outcome: str) -> str:
    """One position per market leg, ever. First sighting wins.

    The board republishes the same ticket every cycle for as long as it qualifies, so
    without this the trial would record the same opinion dozens of times, inflate `n`
    with copies of one bet, and let a later, better price silently replace the one we
    would actually have paid.
    """
    return f"{market_id}:{outcome.strip().lower()}"


def _event_of(row: dict) -> str:
    """Which EVENT a row (or a ticket) belongs to, for the per-event exposure cap.

    The Polymarket event-page url is the venue's own event identifier, and it is the
    only field that groups the markets of one fixture: a moneyline and its O/U carry
    different ids and different titles but the same `/event/mlb-bal-tex-2026-08-07`.
    Falling back to the market id where there is no url (the Kalshi sleeves) makes each
    market its own event, which is the no-op default - safer than a guess that would
    lump unrelated markets under one ceiling.
    """
    url = (row.get("url") or "").strip().lower()
    return url or (row.get("market_id") or "").strip()


def _contracts_of(row: dict) -> int:
    """Contracts a live row represents, derived for rows written before the sizer.

    Rows opened under the old flat-stake path all carry `contracts`; maker intents did
    not, because a pending order only stored its dollar stake. Deriving from the limit
    price rather than assuming zero matters: a resting order IS exposure on its event,
    and counting it as none would let the cap be walked around by leaving orders out.
    """
    c = row.get("contracts")
    if c is None:
        price = float(row.get("price") or row.get("limit_price") or 0.0)
        c = (float(row.get("stake") or 0.0) / price) if price > 0 else 0.0
    return int(round(float(c)))


def _account_for(stake: float) -> sizing.Account:
    """The account the trial's flat stake implies, so the house caps bind at trial scale.

    `sizing.Account` states the risk budget as a FRACTION of capital, and the trial
    states it as a flat dollar stake; the two are the same statement, so the account is
    `stake / per_trade_fraction`. Deriving it rather than hardcoding `Account()` keeps
    the caps proportional to whatever `--stake` the trial is run at, instead of sizing a
    $100 paper book against the sizer's $100,000 default and never binding at all.
    """
    base = sizing.Account()
    return sizing.Account(size=stake / base.per_trade_fraction,
                          daily_loss_limit_fraction=base.daily_loss_limit_fraction,
                          per_trade_fraction=base.per_trade_fraction)


def _block(log: dict, key: str, t: dict, now: float, reason: str, **extra) -> None:
    """Log a ticket the exposure rules refused. Keyed, so it cannot grow unbounded.

    A refusal is evidence - it is the entire point of having the rule - but the board
    republishes a blocked ticket every 15 minutes, so this is a dict updated in place
    rather than a list appended to. `times` is how often the rule fired, which is what
    distinguishes a cap doing real work from one that has never actually bound.

    Blocked keys are deliberately NOT added to `seen`: a per-event cap is a live
    constraint that frees up as positions settle, so the same ticket gets re-judged next
    cycle at the price it would then be paid, rather than being retired on one refusal.
    """
    row = log.get(key)
    if row is None:
        row = log[key] = {"key": key, "market_id": t.get("market_id", ""),
                          "outcome": t.get("outcome", ""), "title": t.get("title", ""),
                          "url": t.get("url", ""), "source": t.get("source") or "whale",
                          "first_at": now, "times": 0}
    row.update({"reason": reason, "last_at": now, **extra})
    row["times"] += 1


def load(path: str | Path) -> dict:
    p = Path(path)
    if not p.exists():
        return {"open": [], "settled": [], "stats": {}}
    data = json.loads(p.read_text(encoding="utf-8"))
    data.setdefault("open", [])
    data.setdefault("settled", [])
    data.setdefault("voided", [])
    data.setdefault("pending", [])
    data.setdefault("blocked", {})
    data.setdefault("stats", {})
    return data


def save(path: str | Path, trial: dict) -> None:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(trial, indent=2), encoding="utf-8")


def record(trial: dict, tickets: list[dict], *, stake: float = DEFAULT_STAKE,
           fee_multiplier: float = 0.07,
           maker_first: bool = False, account: sizing.Account | None = None,
           now: float | None = None) -> int:
    """Open a paper position (or a pending maker order) for each ticket not
    already held. Returns how many were newly recorded, intents included.

    SIZED BY THE HOUSE RULES, not by a flat dollar amount (changed 2026-08-16). The
    trial ran for months at a flat stake while `sizing.py` sat unused, so its
    concentration caps never bound on anything: six legs of one baseball game each took
    a full stake and $600 landed on a single event. Every entry now goes through
    `sizing.size_position` against the account the stake implies, so the per-market and
    per-event ceilings apply to the paper book exactly as they would to a real one.

    The deeper reason is that the trial was scoring a position nobody was ever told to
    place. `build_board` already sizes every published ticket through this same function
    and the page re-sizes it against the reader's own capital - so the board said "buy N
    contracts under the caps" while the record said "$100 flat". Those are different
    bets. They now agree, differing only in account size, which is the one thing that
    SHOULD differ between a $100 paper book and whatever capital a reader has.

    A consequence worth knowing: 19 contracts per $1,000 against a 1% risk budget means
    the per-market cap binds below ~52.6c, so most rows are now sized by contract count
    rather than by dollars, and a longshot stakes less than a coinflip. That is the
    house rule, not an accident of the account chosen - the crossover is a ratio of the
    two constants and is the same at any account size. Per-bet returns stay comparable
    to the flat-staked rows already in the file because a return is scale-free; DOLLAR
    P&L across the 2026-08-16 boundary is not, and should not be added up naively.

    Conviction is passed as 1.0 ON PURPOSE. The sizer can scale a stake by conviction
    and this deliberately does not use that: the module docstring's argument is one
    hypothesis at a time, and the settled rows say conviction does not rank anyway - the
    0.44 bucket made +$852 while the 0.46 bucket lost $1,300. Scaling by a score
    measured not to rank would put the most money on the worst-evidenced bets. What is
    wired in here is the CAPS, which is the part that was missing.

    EVERY INSTANT FILL IS A TAKER FILL (changed 2026-08-17), so there is no longer a
    `maker` argument to get wrong. The branch below writes a row the moment the board
    fires, at `entry_price`, which `signals.py` sets to ``best_ask`` for YES and
    ``1 - best_bid`` for NO - a price you only get by crossing the spread. The maker
    discount now belongs solely to `_open_from_pending`, which reaches that price by
    resting at a bid and watching an ask come to it.
    """
    now = time.time() if now is None else now
    pending = trial.setdefault("pending", [])
    blocked = trial.setdefault("blocked", {})
    account = _account_for(stake) if account is None else account
    expired = (trial.get("maker") or {}).get("expired") or []
    # Pending and expired intents both block re-entry. Pending for the same reason
    # open rows do; expired because "retry until it fills" is exactly the adverse-
    # selection machine this module exists to expose - keep placing the order and
    # the record fills only when the market comes down through it.
    seen = {r["key"] for r in trial["open"]} | {r["key"] for r in trial["settled"]} \
        | {r["key"] for r in pending} | {r["key"] for r in expired}
    # Live exposure, from open positions AND resting intents. Settled rows are excluded
    # on purpose: a resolved market is not a position, so it neither eats event room nor
    # contradicts a new opinion.
    on_event: dict[str, int] = {}
    held_leg: dict[str, set[str]] = {}
    for r in trial["open"] + pending:
        ev = _event_of(r)
        on_event[ev] = on_event.get(ev, 0) + _contracts_of(r)
        held_leg.setdefault(r.get("market_id", ""), set()).add(
            (r.get("outcome") or "").strip().lower())
    added = 0
    for t in tickets:
        price = float(t.get("entry_price") or 0.0)
        if not 0.0 < price < 1.0:
            continue                       # unpriceable: not a position, not a data point
        key = _key(t.get("market_id", ""), t.get("outcome", ""))
        if key in seen:
            continue

        # NEVER BOTH SIDES OF ONE MARKET. `_key` is (market, outcome), so a binary
        # market's two legs are different keys and both used to be recorded - 40 events
        # in the live record ended up held on both sides, a median 7.3 hours apart. That
        # is a guaranteed loss of two fees for a locked payout, and worse as evidence:
        # the signal contradicting itself was being scored as two independent opinions,
        # which is 23% of the whale rows. `build_board` already keeps one opinion per
        # event WITHIN a run; this is the same rule ACROSS runs, which is where every
        # one of those contradictions actually happened.
        mid = t.get("market_id", "")
        side = (t.get("outcome") or "").strip().lower()
        held = held_leg.get(mid)
        if held and side not in held:
            _block(blocked, key, t, now, "opposing side of this market already held",
                   held=sorted(held))
            continue

        ev = _event_of(t)
        bid = float(t.get("bid") or 0.0)
        # Size at what we would actually PAY: the resting bid on a maker-first intent,
        # the ask otherwise. Sizing a limit order off the ask would book contracts we
        # never agreed to buy at a price we never agreed to pay.
        entry = bid if (maker_first and 0.0 < bid < price) else price
        if account.max_contracts_per_event - on_event.get(ev, 0) <= 0:
            _block(blocked, key, t, now, "per-event contract cap already full",
                   event=ev, on_event=on_event.get(ev, 0),
                   cap=account.max_contracts_per_event)
            continue
        sized = sizing.size_position(entry, account, conviction=1.0,
                                     already_on_event=on_event.get(ev, 0))
        if sized is None:
            _block(blocked, key, t, now, "no valid position size at this price",
                   entry=round(entry, 4))
            continue
        contracts = sized.contracts

        base = {
            "key": key,
            "market_id": t.get("market_id", ""),
            "venue": venue_of(t),
            "outcome": t.get("outcome", ""),
            "title": t.get("title", ""),
            "url": t.get("url", ""),
            # What the sized order actually costs, which is at or below the flat stake
            # once a cap bites. Kept as `stake` because it is still the denominator of
            # this row's return - `backtest.evaluate` reads `realized / stake` - so the
            # per-bet figures the deploy gate scores stay scale-free and comparable to
            # every flat-staked row already in the file.
            "stake": round(contracts * entry, 4),
            # Which rule set the size: "risk-budget" means the caps never bound.
            "capped_by": sized.capped_by,
            # Everything below is for slicing the result later, not for scoring it.
            # True = cleared the buy bar and was recommended. False = cleared every hard
            # filter but sat below it. Only the first is evidence about the board as
            # published; both are evidence about where the bar belongs.
            "shown": bool(t.get("_shown", True)),
            # Which hypothesis this row is evidence FOR. The trial now carries two
            # sleeves that share a settlement path and share nothing else, so a pooled
            # win rate would answer neither question - see `stats`.
            "source": t.get("source") or "whale",
            "conviction": t.get("conviction"),
            "n_wallets": t.get("n_wallets"),
            "whale_usd": t.get("whale_usd"),
            "drift_c": t.get("drift_c"),
            "hours_to_resolve": t.get("hours_to_resolve"),
            "liquidity": t.get("liquidity"),
            "end_iso": t.get("end_iso", ""),
            "event_iso": t.get("event_iso", ""),
            **{k: t[k] for k in MODEL_FIELDS if k in t},
            # `is not None` rather than `in t`, because `bridge._carry` copies these by
            # key and writes None where the origin had nothing - a row that says
            # "wallet_usd: null" claims to know something it does not.
            **{k: t[k] for k in SIGNAL_FIELDS if t.get(k) is not None},
            # Bridge rows resolve via the market they were copied FROM (see `main`):
            # a PM-US slug can't be asked Gamma anything, but its origin can.
            "origin_market_id": t.get("origin_market_id", ""),
        }
        if maker_first and 0.0 < bid < price:
            # Maker-first: join the bid instead of crossing to the ask, and record
            # the case for the trade AT INTENT TIME. If this order never fills, the
            # intent - fair value, edge, foregone price - is what the trial keeps,
            # because a record of fills alone drops the unfilled winners and keeps
            # the filled losers, which manufactures edge out of adverse selection.
            pending.append({
                **base,
                "intent_at": now,
                "limit_price": round(bid, 4),
                "intended_price": round(bid, 4),
                "ask_at_intent": round(price, 4),
                # The order is for a contract COUNT, so the count is what rests in the
                # book and what `_open_from_pending` fills - not a dollar figure that
                # would silently re-divide at whatever price the fill came in at.
                "contracts": float(contracts),
                "fair_at_intent": t.get("model_prob"),
                "edge_at_intent": t.get("edge"),
                "polls": 0,
            })
        else:
            base.update({
                "opened_at": now,
                "price": round(price, 4),
                "contracts": float(contracts),
                # TAKER, unconditionally: this row crossed the spread to exist. The
                # trial used to book it at a `Config.assume_maker` flag, since deleted - a
                # quarter of the fee
                # - which flattered the first sample's headline by 1.9 points per bet
                # and was never true of a single row that reached this branch.
                #
                # `_fee_mult` survives because Kalshi does not charge one multiplier:
                # S&P/Nasdaq markets are 0.035 where the general schedule is 0.07, and
                # booking an index row at the general rate would double its cost.
                "fee": trade_fee(price, max(1, contracts),
                                 multiplier=float(t.get("_fee_mult") or fee_multiplier),
                                 maker=False),
            })
            trial["open"].append(base)
        seen.add(key)
        # The caps must bind WITHIN a run too. Tickets arrive from the board sorted by
        # conviction, so a single cycle can carry several legs of one fixture, and
        # updating exposure only between runs would let exactly the concentration this
        # is meant to prevent through the door on the first day it happened.
        on_event[ev] = on_event.get(ev, 0) + contracts
        held_leg.setdefault(mid, set()).add(side)
        added += 1
    return added


def _open_from_pending(trial: dict, row: dict, *, price: float, now: float,
                       taker: bool, fee_multiplier: float) -> None:
    """Turn a pending maker order into an open row at ``price``."""
    # A resting order is for a contract COUNT, so the fill is that count at whatever
    # price it came in at - which is why the stake is recomputed below rather than
    # carried. Intents written before the sizer store only a dollar stake and keep the
    # old derivation; they are the three rows already in `docs/trial.json`.
    stored = row.get("contracts")
    contracts = float(stored) if stored else row["stake"] / price
    if taker:
        fee = trade_fee(price, max(1, round(contracts)),
                        multiplier=fee_multiplier, maker=False)
    else:
        # Maker fills are free on standard markets; `is_designated` is the hook
        # for the few series Kalshi charges 25% of taker on resting orders.
        fee = maker_trade_fee(price, max(1, round(contracts)),
                              multiplier=fee_multiplier,
                              designated=is_designated(row["market_id"]))
    open_row = {k: v for k, v in row.items() if k != "polls"}
    open_row.update({
        "opened_at": now,
        "price": round(price, 4),
        "contracts": round(contracts, 4),
        # A taker fallback crosses at a HIGHER price than the limit, so the same
        # contracts cost more. Carrying the intent's stake would understate what the
        # fill actually cost and inflate this row's return by the width of the spread.
        "stake": round(contracts * price, 4),
        "filled_price": round(price, 4),
        "fill_polls": row["polls"],
        "maker": not taker,
        "fee": fee,
    })
    if taker:
        open_row["maker_fallback"] = True
    trial["open"].append(open_row)


def check_fills(trial: dict, quotes: dict[str, dict], *, max_polls: int = 8,
                fallback_taker: bool = False, fee_multiplier: float = 0.07,
                now: float | None = None) -> tuple[int, int]:
    """Advance every pending maker order one poll. Returns (filled, expired).

    The fill rule is deliberately conservative: a resting bid fills ONLY when a
    later snapshot shows the ask at or through our limit - the market came to us.
    Touches, queue position, and trades inside the spread are all invisible to a
    15-minute poller, and guessing about them would flatter the fill rate on
    exactly the orders adverse selection punishes.

    An order still unfilled after ``max_polls`` either cancels (default) - moving
    to the expired-intent log with its edge-at-intent so unfilled winners cannot
    silently vanish from the record - or, with ``fallback_taker``, crosses the
    spread at the then-current ask at taker fees. A fallback with no live quote
    cancels instead: inventing a price to cross at would be fiction.
    """
    now = time.time() if now is None else now
    still: list[dict] = []
    filled = expired = 0
    for row in trial.setdefault("pending", []):
        row["polls"] = int(row.get("polls") or 0) + 1
        q = quotes.get(row["key"]) or {}
        ask = float(q.get("ask") or 0.0)
        if 0.0 < ask < 1.0 and ask <= row["limit_price"] + 1e-9:
            _open_from_pending(trial, row, price=row["limit_price"], now=now,
                               taker=False, fee_multiplier=fee_multiplier)
            filled += 1
        elif row["polls"] >= max_polls:
            if fallback_taker and 0.0 < ask < 1.0:
                _open_from_pending(trial, row, price=ask, now=now,
                                   taker=True, fee_multiplier=fee_multiplier)
                filled += 1
            else:
                mk = trial.setdefault("maker", {})
                mk.setdefault("expired", []).append({**row, "expired_at": now})
                expired += 1
        else:
            still.append(row)
    trial["pending"] = still
    return filled, expired


def retag_weather_fees(trial: dict, *, multiplier: float = 0.07) -> int:
    """Recharge still-open weather rows at taker fees. Returns how many changed.

    A weather entry takes the ask the moment the model fires - a taker cross by
    construction - but the sleeve's first weeks of rows were booked at the trial-wide
    maker default, 25% of the taker fee. On an 8c bracket that understates cost by
    ~$4.83 per $100 stake, which is ~5 points of phantom edge on the one sleeve that
    is actually Kalshi-tradeable; left alone, the DSR gate would be judging fiction.
    Open rows are positions, not results, so recomputing their fee is a correction
    rather than a rewrite - and settled rows are never touched, both because none
    settled before the fix and because editing settled evidence would be worse than
    the bug. Idempotent: a row already at taker fees recomputes to itself.
    """
    changed = 0
    for row in trial["open"]:
        if source_of(row) != "weather":
            continue
        # Maker-first fills are not taker crosses: their fee was set at fill time
        # by `check_fills` and recharging them here would undo the very accounting
        # the maker-first path exists to record.
        if "fill_polls" in row:
            continue
        fee = trade_fee(row["price"], max(1, round(row["contracts"])),
                        multiplier=multiplier, maker=False)
        if fee != row.get("fee"):
            row["fee"] = fee
            changed += 1
    return changed


def _winner(meta: dict) -> str | None:
    """Name of the winning outcome, or None if this market has not cleanly resolved."""
    if not meta.get("closed"):
        return None
    names = meta.get("outcomes") or []
    prices = meta.get("prices") or []
    if len(names) != len(prices) or not names:
        return None
    winners = [n for n, p in zip(names, prices) if p >= WON_AT]
    losers = [n for n, p in zip(names, prices) if p <= LOST_AT]
    # Exactly one leg at 1 and every other at 0. A market that is closed but still
    # quoting anything in between is mid-resolution or disputed, and saying so is the
    # whole point - a paper record that guesses is worth less than no paper record.
    if len(winners) == 1 and len(losers) == len(names) - 1:
        return winners[0]
    return None


def settle(trial: dict, metas: dict[str, dict], *, now: float | None = None) -> int:
    """Label every open position whose market has resolved. Returns how many."""
    now = time.time() if now is None else now
    still_open, settled = [], 0
    for row in trial["open"]:
        meta = metas.get(row["market_id"]) or {}
        # A voided market never resolves. Holding it would leave a position open
        # forever, quietly inflating the open count with something that can never
        # become evidence - so it leaves the trial and is recorded as withdrawn
        # rather than deleted, because a vanishing row looks like a hidden loss.
        if meta.get("voided"):
            trial.setdefault("voided", []).append({**row, "voided_at": now})
            continue
        winner = _winner(meta)
        if winner is None:
            still_open.append(row)
            continue
        won = winner.strip().lower() == row["outcome"].strip().lower()
        price, contracts, stake, fee = (
            row["price"], row["contracts"], row["stake"], row["fee"])
        realized = (contracts * (1.0 - price) - fee) if won else (-stake - fee)
        trial["settled"].append({
            **row,
            "settled_at": now,
            "winner": winner,
            "won": won,
            # The market's own price at entry. See the module docstring: this makes
            # `calibration_gap` read as realised edge, with negative meaning we beat it.
            "pred": price,
            "realized": round(realized, 4),
        })
        settled += 1
    trial["open"] = still_open
    return settled


# How many price marks one open row keeps. A mark serialises to ~94 bytes at this
# file's indent, and a 15-minute poller would lay down 96 of them a day, so an uncapped
# series costs ~9.0 KB per open row per day - measured 2026-08-17 against the live
# file, that is 421 KB A DAY across the 48 markable open rows, growing without bound in
# a 650 KB record that is committed on every run. Git history is the one thing in this
# project that can never be compacted, so an unbounded series is not a disk problem, it
# is a permanent one. Capped, a row tops out at ~2.3 KB and the whole file gains ~106 KB
# (+16%) once every row has filled its series - a step, not a slope.
#
# Those are the worst-case figures, and the worst case is a book that moves on every
# single poll. `mark_open` extends a standing mark instead of repeating it, so a row
# only spends a mark when its quote actually CHANGES; the daily 96 is a ceiling almost
# nothing reaches, and the cap below is what stops a genuinely jumpy market from
# reaching it either.
#
# 24 is roughly a mark an hour over a day-long hold and a coarse shape over a week-long
# one, which is the resolution the questions in `mark_open` actually need: they are
# about whether a position went underwater and by how much, not about the tick.
MARK_CAP = 24

# How far apart two sightings of the same book may be and still be written as one held
# mark. A poll runs every 15 minutes, so this is one and a half intervals: enough slack
# for a late run - GitHub's scheduler is routinely a few minutes behind - and not enough
# to cover a poll that never produced a quote. Past it the next sighting starts a FRESH
# mark, so the stretch nobody could read shows up as a gap between one mark's `until`
# and the next one's `t`, which is exactly what it is. Without this bound a feed that
# broke for a day and came back to an unchanged book would extend one mark straight
# across the outage and read as "held all day".
MARK_MAX_GAP = 1350


def _leg_quote(meta: dict, outcome: str) -> tuple[float, float] | None:
    """The book for THE LEG THIS ROW BOUGHT, or None when that cannot be established.

    Both settlement adapters publish `best_bid`/`best_ask` for the market's FIRST
    outcome - Gamma's `bestBid`/`bestAsk` quote the yes token, Kalshi's `yes_bid`/
    `yes_ask` say so in the name. Half the open rows in `docs/trial.json` are on the
    other leg, and a binary's two legs are complements with the spread flipped: to buy
    the second leg you pay ``1 - best_bid``, and you can sell it at ``1 - best_ask``.
    Storing the first leg's book on a second-leg row would be the same class of mistake
    as printing a contract count with a dollar sign in front of it - the number is real,
    it just answers a different question than the field name promises, and here it would
    invert the sign of "was this position underwater".

    None rather than a guess in every ambiguous case: an outcome that names neither leg,
    a market that does not quote two of them, a crossed book, or the all-zero quote that
    an absent field is indistinguishable from (`kalshi.market_meta` warns about exactly
    that). A missing mark is a gap in the series; a wrong one is a false answer.
    """
    names = [str(n).strip().lower() for n in (meta.get("outcomes") or [])]
    want = (outcome or "").strip().lower()
    if len(names) != 2 or want not in names:
        return None
    try:
        bid = float(meta.get("best_bid"))
        ask = float(meta.get("best_ask"))
    except (TypeError, ValueError):
        return None
    if not 0.0 <= bid <= ask <= 1.0 or (bid <= 0.0 and ask <= 0.0):
        return None
    return (bid, ask) if names.index(want) == 0 else (1.0 - ask, 1.0 - bid)


def _thin_marks(marks: list[dict], cap: int) -> list[dict]:
    """Drop marks until at most ``cap`` remain, keeping first, last, min and max.

    Those four are kept because they are the ones the series exists to answer for.
    "Was this position ever underwater" is a question about the EXTREMES - the worst
    mid the row ever printed against the price it was opened at - and a thinning rule
    that sampled evenly would delete exactly the spike it was asked about while keeping
    the flat hours either side of it. First and last are kept for the same reason in
    time: they bound the hold, so entry timing and the price at settlement stay
    answerable however hard the middle is thinned.

    The rest of the budget is spent on the widest TIME gap each pass, not the widest
    stretch of list positions. A thinned series is no longer evenly spaced, so bisecting
    by index would compound its unevenness a little more on every poll until the record
    was dense around one afternoon and blank across the days on either side.

    Those four are a FLOOR, not a target: a ``cap`` below four returns all four anyway,
    because a cap that could only be met by dropping the high, the low or an endpoint
    would be saving bytes by deleting the answer rather than the padding.
    """
    if len(marks) <= cap:
        return marks
    mids = [(m["best_bid"] + m["best_ask"]) / 2.0 for m in marks]
    kept = sorted({0, len(marks) - 1, mids.index(min(mids)), mids.index(max(mids))})
    while len(kept) < cap:
        # Only gaps with a mark still inside them are candidates; the widest gap in the
        # series may already be a pair of neighbours, and stopping there would leave the
        # budget unspent while marks that could have been kept were thrown away.
        gaps = [i for i in range(len(kept) - 1) if kept[i + 1] - kept[i] > 1]
        if not gaps:
            break
        i = max(gaps, key=lambda j: marks[kept[j + 1]]["t"] - marks[kept[j]]["t"])
        lo, hi = kept[i], kept[i + 1]
        target = (marks[lo]["t"] + marks[hi]["t"]) / 2.0
        kept.insert(i + 1, min(range(lo + 1, hi),
                               key=lambda j: abs(marks[j]["t"] - target)))
    return [marks[i] for i in kept]


def mark_open(trial: dict, metas: dict[str, dict], *, now: float | None = None,
              cap: int = MARK_CAP, max_gap: float = MARK_MAX_GAP) -> int:
    """Mark every open row the batch quote can price. Returns how many were priced.

    A row whose book has MOVED gains a mark; a row whose book is exactly where the last
    mark left it has that mark's ``until`` extended instead, so a flat position costs one
    changed number per poll rather than a repeated five-line entry. Both count as priced,
    because the question this number answers is how many rows the batch could quote.

    THE RECORD HAD NO PRICE PATH AT ALL. Across the 585 settled and open rows there is
    an entry price and a settlement and nothing in between - not a bid, not an ask, not
    a spread - so a whole class of question about it is not merely unanswered but
    unaskable: was the position ever underwater, would any exit rule have helped, what
    did the spread cost, did entry timing matter. None of those can be back-filled later
    from anywhere, because a quote that was not written down when it was live is gone.

    THIS IS NOT AN EDIT, and the distinction is the one this module is built on. A
    settled row is a committed RESULT and is never rewritten - see `on_taker_fees`,
    which corrects fees on score-time copies rather than touch a recorded row. A mark is
    a new observation appended to a position that is still open and still has no result,
    which is the same thing `record` does when it opens a row: added data, not altered
    data. Marks freeze at settlement structurally rather than by a rule anyone has to
    remember - this loops over ``trial["open"]``, and `settle` has already moved every
    row it resolved into ``trial["settled"]`` by the time this runs, so a settled row is
    not reachable from here at all. Thinning only ever drops marks from a row that is
    still open, and the file it lands in is committed every 15 minutes, so the history
    of what was dropped is in the git log either way.

    FORWARD-ONLY. Rows already in the file start their series at the next poll and
    nothing is retro-filled: a mark claims a quote was READ at time t, and inventing one
    for a Tuesday last month would be fabricating the very evidence this adds.

    NO EXTRA NETWORK CALL. ``metas`` is the batch the settle path has already fetched
    for exactly these rows, and it carries the live book alongside the resolution
    fields. This runs every 15 minutes in CI over ~52 open rows; a per-row quote fetch
    would be 52 round trips a run to learn what one batch already knows.
    """
    now = time.time() if now is None else now
    marked = 0
    for row in trial["open"]:
        # PM-US bridge rows settle against their ORIGIN market's metadata (see `main`),
        # because PM-US has no public resolution endpoint here. That substitution is
        # sound for "did it resolve, and which way" - the same contract resolves the
        # same way on both venues - and unsound for a price: the venue basis between
        # them is a real number, and it is one of the things the bridge exists to
        # measure. Marking a PM-US row with the international book would bake that
        # basis into the row as if it were drift.
        if venue_of(row) == "polymarket-us":
            continue
        quote = _leg_quote(metas.get(row["market_id"]) or {}, row.get("outcome", ""))
        if quote is None:
            continue
        bid, ask = round(quote[0], 4), round(quote[1], 4)
        marks = row.setdefault("marks", [])
        last = marks[-1] if marks else None
        seen = last.get("until") or last["t"] if last else 0
        if (last and last["best_bid"] == bid and last["best_ask"] == ask
                and now - seen <= max_gap):
            # THE QUOTE HAS NOT MOVED, so the standing mark is extended rather than
            # duplicated: it reads "this book, from `t`, still there at `until`". Most
            # 15-minute polls find the book exactly where they left it, and appending an
            # identical mark for each one costs ~5 changed lines per row on a file that
            # is committed every 15 minutes - measured 2026-08-17, ~252 lines a commit
            # across the open rows, on top of the 73-240 a board refresh already moves.
            # Git history is the one thing here that can never be compacted, so the
            # churn is the durable cost, not the bytes.
            #
            # `until` is why this is a dedup and not a data loss. The alternative -
            # simply skipping - makes a gap mean either "the price held" or "the quote
            # was unreadable", and those are opposite facts about the position. With
            # `until`, a hold is stated and a gap still means only what it meant before -
            # which is also why `max_gap` exists: a sighting too far from the last one is
            # a new mark, so an outage cannot be absorbed into a claim that it held.
            #
            # Extending it is not a rewrite of a committed result. `t`, `best_bid` and
            # `best_ask` never change once written, this row is still OPEN and has no
            # result to contradict, and `until` only ever moves forward - it records
            # that an observation kept holding, which is the same added-data act as
            # appending would have been.
            last["until"] = round(now)
            marked += 1
            continue
        # Seconds, not fractions of one: the poll interval is 15 minutes, so anything
        # finer is a decimal place of noise paid for on every commit, forever.
        marks.append({"t": round(now), "best_bid": bid, "best_ask": ask})
        if len(marks) > cap:
            row["marks"] = _thin_marks(marks, cap)
        marked += 1
    return marked


def source_of(row: dict) -> str:
    """Which sleeve a row belongs to, inferred when the row predates the field."""
    return (row.get("source") or "").strip().lower() or "whale"


# Sleeves that have been switched off after being scored. Their rows STAY in the file -
# a track record that deletes its losers is worth nothing, and in a public git repo the
# deletion would not even hide them, it would just publish a diff of losing rows being
# removed. They are excluded from the HEADLINE instead, because the headline's job is to
# answer "how does the bot that runs tomorrow perform", and no sleeve that is switched
# off runs tomorrow. The pooled all-time number is kept alongside, under
# `including_retired`, so nothing is quietly lost. Retiring a sleeve is therefore an
# append to this set plus a config flag - never an edit to the settled rows.
RETIRED_SOURCES = frozenset({"weather"})


# Retired MARKET CLASSES: the same holdout, for a cut that does not line up with a
# sleeve. `RETIRED_SOURCES` keys on `source`, which can only express "this sleeve is
# off" - and esports was never a sleeve. Those rows arrive through the whale sleeve and
# its Polymarket US mirror, so when esports was cut at the gate on 2026-08-16 the record
# kept scoring it: 127 settled rows worth -$1,904 and -15.0% per bet stayed inside a
# headline whose entire claim is that it describes the bot that runs tomorrow. It does
# not bet those markets tomorrow. Holding weather out and esports in was not a judgement
# call, it was the data model - which is exactly the kind of accident that flatters a
# record without anyone deciding to.
#
# The predicate is `is_esports` itself, the SAME classifier the board rejects on, called
# on the row's title and event url (`is_esports` reads slug prefixes like `/cs2-`, which
# is the only thing that identifies a derivative market such as "Game Handicap: NS
# (-1.5) vs DN SOOPers (+1.5)"). One implementation means what the record holds out and
# what the gate refuses cannot drift apart; a second copy of that regex would eventually
# disagree with the first, and the direction it disagreed in would be nobody's decision.
#
# The bar for adding an entry here is the same as for `RETIRED_SOURCES` and higher than
# it looks: a class removed from the headline must actually be OFF at the gate, or the
# headline stops describing the live bot in the other direction.
RETIRED_CLASSES: tuple[tuple[str, Callable[[dict], bool]], ...] = (
    ("esports", lambda row: is_esports(row.get("title", ""), row.get("url", ""))),
    # Venue mirrors of markets where the title's team is NOT the outcome bet on -
    # handicaps, spreads, totals, map/game/set legs. The bridge matched these by name
    # onto the destination's PLAIN market, so the row records our price against someone
    # else's question, and the realized returns say so: -105.7%, -101.2%, +136.9% and
    # +727.2% on four rows. That dispersion is not a run of bad bets, it is a mis-mapped
    # outcome - and it is also where every 24-28c "arbitrage" this record has shown
    # between venues came from. The widest gap on any plain market is 6.5c.
    #
    # Mirrors ONLY (`origin_market_id`), because only the mirror is off at the gate:
    # `bridge.build_bridge_tickets` now refuses to mirror these, but the whale sleeve
    # still bets the origin market itself, so an origin row on a spread stays in the
    # headline. Holding it out too would break the rule stated above the esports entry -
    # a class removed from the headline must actually be OFF at the gate, or the headline
    # stops describing the live bot in the other direction.
    #
    # Three of the four are esports mirrors the esports entry cannot see: the mirror's
    # url is `polymarket.us/market/<slug>`, carrying no `/cs2-` prefix, and its title
    # carries no game name, so neither field `is_esports` reads survives the crossing.
    # The origin rows were retired correctly; only their reflections leaked.
    ("derivative-mirror",
     lambda row: bool(row.get("origin_market_id"))
     and is_derivative_title(row.get("title", ""))),
)


def retired_as(row: dict) -> str:
    """Which retired bucket holds this row out of the headline, or "" if it is live.

    Sources are checked before classes so a row can only ever land in one bucket, which
    is what keeps `by_source` a partition of the file: every settled row is counted in
    exactly one slice, and the slices still sum to `including_retired`.
    """
    src = source_of(row)
    if src in RETIRED_SOURCES:
        return src
    for name, matches in RETIRED_CLASSES:
        if matches(row):
            return name
    return ""


# The two schedules a row could honestly have been booked at. Order matters below only
# in that TAKER is tried first: at some prices the maker and taker fees round to the same
# cent, and a row that is already right must never be "corrected".
_FEE_MULTIPLIERS = (DEFAULT_FEE_MULTIPLIER, INDEX_FEE_MULTIPLIER)


def rested_and_filled(row: dict) -> bool:
    """Did this row EARN the maker discount by resting in the book until an ask came?

    The only path that can answer yes is `_open_from_pending`, which writes both fields
    below at fill time - `maker` False on a taker fallback that crossed after the intent
    expired, True on a genuine resting fill. Everything else opened at the ask.
    """
    if "maker" in row:
        return bool(row["maker"])
    return "fill_polls" in row          # fills recorded before `maker` was written


def corrected_fee(row: dict) -> float | None:
    """The fee ``row`` should carry, or None when that cannot be established.

    None is not an error and not a zero: it means the recorded fee matches neither
    schedule at either multiplier (a hand-written row, a shape from before the fee model,
    a price or contract count that is missing or nonsensical), and the caller must fall
    back to the number actually recorded. Guessing at a row we cannot reproduce would put
    fiction into the headline in the name of correcting it.
    """
    if rested_and_filled(row):
        return row.get("fee")           # the maker branch was legitimate here
    recorded = row.get("fee")
    try:
        price = float(row.get("price"))
        contracts = max(1, round(float(row.get("contracts"))))
        recorded = float(recorded)
    except (TypeError, ValueError):
        return None
    if not 0.0 < price < 1.0:
        return None
    # Identify the schedule by exact match rather than by assuming a multiplier, because
    # the multiplier is not recorded on the row: `_fee_mult` is a ticket-time override
    # that never reached the file. A row that already matches taker is returned unchanged.
    fees = [(mult, trade_fee(price, contracts, multiplier=mult, maker=False))
            for mult in _FEE_MULTIPLIERS]
    for _, taker in fees:
        if abs(recorded - taker) < 1e-9:
            return recorded
    for mult, taker in fees:
        if abs(recorded - trade_fee(price, contracts, multiplier=mult,
                                    maker=True)) < 1e-9:
            return taker
    return None


def on_taker_fees(rows: list[dict]) -> list[dict]:
    """Score-time COPIES of ``rows``, recharged at the fee the fill actually incurred.

    THE RECORDED ROWS ARE NEVER TOUCHED, and that is the whole design. This trial's one
    claim over a spreadsheet is that every row was committed once, at open time, and
    never edited afterwards - a claim that survives exactly as long as nothing edits a
    row, including a correction that is genuinely right. So the arithmetic happens here,
    on copies, every time the stats are built, and anyone can re-derive it from the file
    as published. `fee_as_recorded` rides along on the copy so the delta stays visible.
    """
    out: list[dict] = []
    for row in rows:
        fee = corrected_fee(row)
        recorded = row.get("fee")
        if fee is None or recorded is None or fee == recorded or "realized" not in row:
            out.append(row)
            continue
        out.append({**row, "fee": fee, "fee_as_recorded": recorded,
                    "realized": round(row["realized"] + recorded - fee, 4)})
    return out


def opinion_id(row: dict) -> str:
    """The identity a row shares with every venue that mirrored the same opinion.

    A mirror is identified by the key its ORIGIN was recorded as, built with `_key`
    rather than by formatting the two fields here, so the string cannot drift from the
    one on the origin row. Everything else is identified by its own `key`, which `_key`
    already guarantees is one row per market leg ever - so a row with no mirror is alone
    under its own identity by construction.

    Split out of `per_opinion` because the Trial page has to group the SAME rows the same
    way to slice its own windows, and it is handed this function's answer as
    `stats["opinion_of"]` rather than carrying a copy of the rule in JavaScript - the
    same reason `retired_keys` and `fee_adjustment` are published.
    """
    origin = row.get("origin_market_id")
    if origin:
        return _key(origin, row.get("outcome", ""))
    return row.get("key") or _key(row.get("market_id", ""), row.get("outcome", ""))


def per_opinion(rows: list[dict]) -> list[dict]:
    """Score-time COPIES of ``rows``, one per OPINION rather than one per fill.

    The venue bridge mirrors a single opinion onto a second venue, so the same view of
    the same question arrives as two rows. Scoring them as two rows tells the deploy gate
    it has seen two independent draws, and independence is the one thing the gate is
    actually measuring: n feeds the DSR's deflation term and the bootstrap resamples the
    list. 376 headline rows are 263 opinions, so the gate was being handed 113 draws that
    do not exist - not a bigger sample, the same sample counted twice.

    A group collapses to what ONE position across both venues would have earned: stakes
    and P&L summed, `pred` stake-weighted, `won` taken from the leg that carried the most
    money. Singleton groups are passed through untouched rather than rebuilt, so this is
    a no-op on a record with no mirrors. Kept in `opened_at` order because the block
    bootstrap resamples runs and would otherwise be reordering the history it samples.

    Like `on_taker_fees`, this never touches a recorded row - see that docstring for why
    that rule is the trial's only real claim over a spreadsheet.
    """
    groups: dict[str, list[dict]] = {}
    for row in rows:
        groups.setdefault(opinion_id(row), []).append(row)

    out: list[dict] = []
    for legs in groups.values():
        if len(legs) == 1:
            out.append(legs[0])
            continue
        stake = sum(leg.get("stake") or 0.0 for leg in legs)
        if stake <= 0:                      # nothing to weight by; leave them alone
            out.extend(legs)
            continue
        lead = max(legs, key=lambda leg: leg.get("stake") or 0.0)
        out.append({**lead,
                    "opened_at": min(leg["opened_at"] for leg in legs),
                    "stake": stake,
                    "realized": round(sum(leg.get("realized") or 0.0 for leg in legs), 4),
                    "won": lead.get("won"),
                    "pred": sum((leg.get("pred") or 0.0) * (leg.get("stake") or 0.0)
                                for leg in legs) / stake,
                    "venues": len(legs)})
    out.sort(key=lambda r: r.get("opened_at") or 0)
    return out


# When the rules the bot bets by actually CHANGED, as UTC seconds. Published with the
# stats so the Trial page can slice its headline into "before" and "since" without
# hardcoding dates in JavaScript that would rot the moment a lever moves.
#
# `at` is the COMMIT time of the change, which is within a minute of the push and so of
# the first board run under the new rules - the board publishes every 15 minutes, so a
# finer boundary than that would be false precision. A row belongs to the window its
# `opened_at` falls in, never its `settled_at`: the question these windows answer is
# "which rules picked this bet", and a position opened on Monday and resolved on Friday
# was chosen by Monday's rules.
#
# Adding an entry here is a claim that the change could plausibly move the record. Keep
# it to real regime changes; a slice of the record per bugfix is how a track record gets
# mined for a flattering window, which is the exact failure this project keeps guarding
# against. The page says so, and deliberately does NOT re-run the deploy gate per slice.
CHANGE_POINTS: tuple[dict, ...] = (
    {"key": "bridge", "at": 1786550946, "commit": "02d129b",
     "label": "venue bridge",
     "note": "Whale tickets started being mirrored onto Polymarket US and Kalshi at "
             "their live asks, so the record stopped being one venue's prices."},
    # This note used to blame the window's -14.24% on the five levers by name. Checked
    # against the file, all five touched sleeves that are retired or that never fired:
    # no gas or SPX row has ever been recorded, no row carries a de-vig or calibration
    # field except three retired weather rows, and the whale tickets carry no `bid`, so
    # the maker-first path could not engage. Whatever moved that window, it was not
    # these. Naming a different cause with the same confidence would just be the same
    # mistake pointed somewhere else, so the note now stops at what is measured.
    {"key": "levers", "at": 1786666818, "commit": "9bb37b3",
     "label": "five levers",
     "note": "Maker-first resting orders, power/Shin de-vig, the SPX 0DTE density "
             "sleeve, the calibration overlay, and the AAA gas sleeve merged on one "
             "night. None of them reached the headline population: they touched only "
             "sleeves since retired or sleeves that never recorded a row, and the whale "
             "path was unchanged across this window. The move here is unexplained."},
    {"key": "weather", "at": 1786819577, "commit": "c3bf50c",
     "label": "weather cut",
     "note": "The weather sleeve was switched off after its thesis was measured and "
             "found false. Its rows are still on file but are held out of the "
             "headline, in every window."},
    {"key": "sizing", "at": 1786903251, "commit": "fca4239",
     "label": "sizing + exposure rules",
     "note": "Positions are sized by the house rules instead of a flat $100, both "
             "sides of one market can no longer be held at once, and esports is cut. "
             "Dollar P&L does not compare across this line; per-position returns do."},
    {"key": "takerfees", "at": 1786924800, "commit": "pending",
     "label": "fees charged as taken",
     "note": "Entries are priced at the ask and were being charged the Kalshi MAKER "
             "fee, a quarter of taker, on fills that crossed the spread by "
             "construction. 287 of the 376 settled rows in the headline were booked "
             "that way. Fees are now charged as taker on every instant fill, and the "
             "settled rows - which are never edited - are recharged at scoring time. "
             "The headline goes from +3.14% to +1.27% per bet. This is an accounting "
             "correction only: no bet was picked, sized or timed differently, and it "
             "makes the record worse, which is the point of running it."},
)


def stats(trial: dict, *, min_n: int = 30) -> dict:
    """Score the settled rows with the project's existing gate, plus trial bookkeeping.

    The headline covers what is still ACTIVE - every retired sleeve (`RETIRED_SOURCES`)
    and every retired market class (`RETIRED_CLASSES`) is held out of it, settled rows
    and open positions alike; the all-time pooled figure lives in `including_retired`.
    `by_source` is still where any decision belongs, and it reports every bucket
    including the retired ones. The sleeves make different claims on different markets
    with different holding periods; a pooled win rate that mixes a six-month Polymarket
    resolution with a next-day Kalshi temperature is arithmetic, not evidence. Whichever
    sleeve reaches `min_n` first gets judged first.

    EVERY FIGURE HERE IS ON CORRECTED FEES (`on_taker_fees`), including the deploy gate,
    the DSR and the bootstrap CI - the decision has to be made on what the fills cost,
    not on what they were mistakenly booked at. The as-published numbers are kept beside
    them under `as_recorded` rather than dropped, because "the headline was 3.1% and is
    now 1.3%, here is both" is the audit trail; silently restating it is not.
    """
    from .backtest import evaluate

    live = [r for r in trial["settled"] if not retired_as(r)]
    live_open = [r for r in trial["open"] if not retired_as(r)]

    out = evaluate(per_opinion(on_taker_fees(live)), min_n=min_n)
    # Both corrections are applied in one order and only one order: recharge the fills
    # first, THEN collapse. Collapsing first would sum fees across venues and leave
    # `corrected_fee` unable to match either schedule, so every mirrored group would fall
    # back to its recorded fee and quietly keep the discount this correction removes.
    #
    # `n` here counts OPINIONS, so it no longer equals the settled row count and no
    # longer sums across `by_source` below. That is the point rather than a wart: the
    # gate's question is how many independent draws support the edge, and the breakdown's
    # question is what each sleeve did. Row counts stay in `as_recorded` and `by_source`.
    out["opinions"] = out["n"]
    out["settled_rows"] = len(live)
    # What the file itself says, unmodified, for anyone checking the correction rather
    # than trusting it. The gate above does NOT read this.
    out["as_recorded"] = evaluate(live, min_n=min_n)
    # Per-row deltas, so the Trial page can slice its own windows on the corrected basis
    # without a second fee model in JavaScript - the same reason `retired_keys` is
    # published. Sign convention: ADD this to the row's recorded `realized`.
    out["fee_adjustment"] = {
        r["key"]: round(corrected["fee_as_recorded"] - corrected["fee"], 4)
        for r, corrected in zip(trial["settled"] + trial["open"],
                                on_taker_fees(trial["settled"] + trial["open"]))
        if r.get("key") and "fee_as_recorded" in corrected}
    # Which rows are the same opinion arriving twice, so the Trial page can collapse its
    # own windows the way `per_opinion` collapses the headline. Published for the reason
    # `retired_keys` is: the rule is a classifier, and a copy of it in JavaScript would
    # be free to disagree with this one - which is exactly how the page came to show
    # +0.1%/bet while this block said -0.8%. Only rows that actually share an identity
    # with another row appear; a key absent from this map is alone by definition, so the
    # map stays a few dozen entries rather than one per row.
    _ids = [(r["key"], opinion_id(r)) for r in trial["settled"] + trial["open"]
            if r.get("key")]
    _mirrored = {i for i, c in Counter(i for _, i in _ids).items() if c > 1}
    out["opinion_of"] = {k: i for k, i in _ids if i in _mirrored}
    out["open_positions"] = len(live_open)
    out["retired_sources"] = sorted(RETIRED_SOURCES)
    out["retired_classes"] = [name for name, _ in RETIRED_CLASSES]
    out["retired_excluded"] = len(trial["settled"]) - len(live)
    # Every held-out row named by key, because the Trial page slices the SAME rows into
    # its own windows and has to hold out exactly what Python holds out. A retired
    # source it can match on the `source` field; a retired class it cannot, and a copy
    # of the classifier in JavaScript would be a second implementation free to disagree
    # with this one. Naming the rows instead means the page cannot get it wrong.
    out["retired_keys"] = sorted(
        r["key"] for r in trial["settled"] + trial["open"]
        if r.get("key") and retired_as(r))
    # Shipped alongside the numbers rather than kept in the page, so the "before/since"
    # windows on the Trial page can only ever name changes that really happened.
    out["changes"] = [dict(c) for c in CHANGE_POINTS]
    # The all-time record, pooled across every sleeve that ever ran. Reported rather
    # than discarded: the headline answers "what runs tomorrow", this answers "what did
    # this project actually do", and the gap between them is itself the audit trail.
    if len(live) != len(trial["settled"]):
        out["including_retired"] = evaluate(
            per_opinion(on_taker_fees(trial["settled"])), min_n=min_n)
    if trial["settled"]:
        span = max(r["settled_at"] for r in trial["settled"]) - \
            min(r["opened_at"] for r in trial["settled"])
        out["trial_days"] = round(span / 86400.0, 1)

    # Bucketed by `retired_as(row) or source_of(row)`, so a retired class becomes its own
    # slice instead of staying inside the sleeve it arrived through. That is what makes
    # these numbers reconcile: `by_source["whale"]` now means the live whale sleeve, the
    # one the headline is built from, and the retired buckets are what the headline drops.
    # Leaving esports inside "whale" would have published a sleeve number that no longer
    # matched the sleeve - the headline saying one thing and its own breakdown another.
    sleeves: dict[str, list[dict]] = {}
    for row in trial["settled"]:
        sleeves.setdefault(retired_as(row) or source_of(row), []).append(row)
    open_by: dict[str, int] = {}
    for row in trial["open"]:
        src = retired_as(row) or source_of(row)
        open_by[src] = open_by.get(src, 0) + 1
    retired_names = set(RETIRED_SOURCES) | {name for name, _ in RETIRED_CLASSES}
    out["by_source"] = {}
    for src in sorted(set(sleeves) | set(open_by)):
        sliced = evaluate(on_taker_fees(sleeves.get(src, [])), min_n=min_n)
        sliced["open_positions"] = open_by.get(src, 0)
        # Flagged, not dropped. A reader who only ever sees the headline should still
        # be able to find the sleeve that was switched off, and why the two top-line
        # numbers differ.
        if src in retired_names:
            sliced["retired"] = True
        out["by_source"][src] = sliced
    out["maker"] = maker_stats(trial)
    out["exposure"] = exposure_stats(trial)
    return out


def exposure_stats(trial: dict) -> dict:
    """What the exposure rules refused, by reason. Published, not logged.

    A cap that never fires is a cap that is not doing anything, and a cap that fires on
    everything has become an off switch - neither is visible from the settled rows,
    because a blocked ticket leaves no row. `distinct` counts tickets; `times` counts
    republished sightings of them, so the two together say whether one stubborn ticket
    or many different ones are hitting the rule.
    """
    blocked = trial.get("blocked") or {}
    by_reason: dict[str, dict[str, int]] = {}
    for row in blocked.values():
        r = by_reason.setdefault(row.get("reason") or "unknown",
                                 {"distinct": 0, "times": 0})
        r["distinct"] += 1
        r["times"] += int(row.get("times") or 0)
    return {"blocked": len(blocked), "by_reason": by_reason}


def maker_stats(trial: dict) -> dict:
    """The maker-first simulation's own scoreboard, fills and non-fills alike.

    The number that matters most here is the pairing of `fill_rate` with
    `foregone_edge`: a high fill rate with low foregone edge says passive entry
    is nearly free; a low fill rate with high foregone edge says the maker
    saving is being paid for in missed trades, which no per-fill fee number
    would ever reveal on its own.
    """
    rows = trial["open"] + trial["settled"] + (trial.get("voided") or [])
    fills = [r for r in rows if r.get("maker") and "fill_polls" in r]
    fallbacks = [r for r in rows if r.get("maker_fallback")]
    expired = (trial.get("maker") or {}).get("expired") or []
    resolved = len(fills) + len(fallbacks) + len(expired)
    return {
        "pending": len(trial.get("pending") or []),
        "filled": len(fills),
        "fallback": len(fallbacks),
        "expired": len(expired),
        "fill_rate": round(len(fills) / resolved, 4) if resolved else None,
        "avg_fill_polls": round(sum(r["fill_polls"] for r in fills) / len(fills), 2)
        if fills else None,
        # Edge the record walked away from by not chasing: the sum of edge-at-
        # intent over every cancelled order. Read it against the fee savings.
        "foregone_edge": round(sum(float(r.get("edge_at_intent") or 0.0)
                                   for r in expired), 4),
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="predictionedge.papertrial")
    ap.add_argument("--board", default="docs/board.json")
    ap.add_argument("--trial", default="docs/trial.json")
    ap.add_argument("--stake", type=float, default=DEFAULT_STAKE)
    ap.add_argument("--no-settle", action="store_true",
                    help="record new tickets but skip the settlement fetch")
    args = ap.parse_args(argv)

    from .config import Config
    cfg = Config.from_env()
    trial = load(args.trial)
    repriced = retag_weather_fees(trial, multiplier=cfg.fee_multiplier)
    if repriced:
        print(f"repriced {repriced} open weather row(s) at taker fees")

    board = json.loads(Path(args.board).read_text(encoding="utf-8"))
    # Stamp positions with when the board SAW that price, not when this process ran.
    # They differ whenever a scheduled run is skipped or the board is replayed, and the
    # hold time is what the whole trial measures - dating an entry to the replay would
    # quietly shorten every holding period in the record.
    # `probe` sits below the buy bar. Recording it is the whole point: a threshold can
    # only be validated against outcomes on BOTH sides of it. Observe above the cutoff
    # alone and 0.45 stays unfalsifiable forever, however much data accumulates.
    # The weather sleeve arrives already filtered to what cleared its own edge bar, so
    # every row is `_shown`; it has no probe tier because its bar is a modelled edge
    # rather than a hand-set conviction cutoff that needs validating from both sides.
    # The weather, gas and spxindex sleeves arrive already filtered to what cleared their
    # own modelled edge bar, so every row is `_shown`; they have no probe tier because
    # their bar is a modelled edge rather than a hand-set conviction cutoff that needs
    # validating from both sides. They no longer need a `_maker: False` override either -
    # `record` charges taker on every instant fill now, which is what these always were.
    # The spxindex sleeve still needs `_fee_mult`: its markets sit on Kalshi's 0.035
    # index schedule rather than the general 0.07 - see `record`.
    flow = [{**t, "_shown": True} for t in (board.get("tickets") or [])] + \
           [{**t, "_shown": False} for t in (board.get("probe") or [])] + \
           [{**t, "_shown": True} for t in (board.get("weather") or [])] + \
           [{**t, "_shown": True} for t in (board.get("gas") or [])] + \
           [{**t, "_shown": True, "_fee_mult": INDEX_FEE_MULTIPLIER}
            for t in (board.get("spxindex") or [])]

    # Maker-first: this run's board IS the next 15-minute snapshot of every market a
    # pending order is resting in, so pending orders are checked against it BEFORE new
    # tickets are recorded - a fill can only come from a strictly later poll than the
    # intent. A market that dropped off the board contributes no quote, which reads as
    # "did not come to us" and counts the poll toward expiry; conservative on purpose.
    filled = expired = 0
    if cfg.maker_first:
        quotes = {_key(t.get("market_id", ""), t.get("outcome", "")):
                  {"bid": t.get("bid"), "ask": float(t.get("entry_price") or 0.0)}
                  for t in flow}
        filled, expired = check_fills(
            trial, quotes, max_polls=cfg.maker_max_polls,
            fallback_taker=cfg.maker_fallback_taker,
            fee_multiplier=cfg.fee_multiplier,
            now=board.get("generated_at") or None)

    added = record(trial, flow, stake=args.stake,
                   fee_multiplier=cfg.fee_multiplier,
                   maker_first=cfg.maker_first,
                   now=board.get("generated_at") or None)

    # The venue bridge: every SHOWN whale ticket is re-recorded at the live ask on
    # the venues a US person can actually trade. Probe and weather rows are excluded -
    # probe is below the buy bar, and weather is already a Kalshi position. The whole
    # sleeve reads public quote endpoints only; a network failure here costs coverage
    # (and is logged as such), never correctness.
    if cfg.bridge_enabled and board.get("tickets"):
        from . import bridge as _bridge
        from .kalshi import _default_fetch as _kx_fetch
        from .polymarket_us import PolymarketUSClient
        b_tickets, attempts = _bridge.build_bridge_tickets(
            board["tickets"],
            pmus_client=PolymarketUSClient(),
            kalshi_fetch=_kx_fetch,
            series_map=_bridge.parse_series_env(cfg.bridge_kalshi_series),
            skip=_bridge.permanent_skips(trial))
        added += record(trial, b_tickets, stake=args.stake,
                        fee_multiplier=cfg.fee_multiplier,
                        now=board.get("generated_at") or None)
        _bridge.update_log(trial, attempts,
                           now=board.get("generated_at") or time.time())

    settled = marked = 0
    if not args.no_settle and trial["open"]:
        # Only open positions need a lookup, and they are the markets that have
        # dropped OFF the board - a resolved market is exactly the one the board
        # stopped showing, so this cannot be answered from board.json.
        #
        # Routed by venue because the two exchanges answer different questions with
        # different keys. Sending a Kalshi ticker to Gamma does not error, it returns
        # NOTHING - which reads as "not resolved yet" and would park every Kalshi row
        # open forever. Merging into one dict is safe: a Polymarket key is `0x`+64 hex
        # and a Kalshi ticker is not, so the two id spaces cannot collide.
        ids: dict[str, list[str]] = {}
        for r in trial["open"]:
            ids.setdefault(venue_of(r), []).append(r["market_id"])
        metas: dict[str, dict] = {}
        if ids.get("polymarket"):
            from .gamma import market_meta as pm_meta
            metas.update(pm_meta(ids["polymarket"]))
        if ids.get("kalshi"):
            from .kalshi import market_meta as kx_meta
            metas.update(kx_meta(ids["kalshi"]))
        # Bridge rows on PM-US settle by their ORIGIN market: PM-US has no public
        # resolution endpoint here, but the row is by construction the same contract
        # as the intl market it was copied from, so Gamma's answer for the origin IS
        # the answer - keyed back under the PM-US row's own market_id.
        pmus_rows = [r for r in trial["open"]
                     if venue_of(r) == "polymarket-us" and r.get("origin_market_id")]
        if pmus_rows:
            from .gamma import market_meta as pm_meta
            origin = pm_meta(sorted({r["origin_market_id"] for r in pmus_rows}))
            for r in pmus_rows:
                meta = origin.get(r["origin_market_id"])
                if meta:
                    metas[r["market_id"]] = meta
        settled = settle(trial, metas)
        # The same batch, used twice. `metas` carries the live book beside the
        # resolution fields, so the rows that did NOT settle can be marked at the price
        # they are trading at right now for free - and after `settle`, so that a row
        # resolved on this poll is already out of `trial["open"]` and its marks are
        # frozen by construction rather than by a rule.
        marked = mark_open(trial, metas)

    trial["stats"] = stats(trial)
    trial["generated"] = time.strftime("%Y-%m-%d %H:%M:%S")
    save(args.trial, trial)

    s = trial["stats"]
    held = ", ".join(s.get("retired_sources", []) + s.get("retired_classes", []))
    print(f"recorded {added} new, settled {settled}, marked {marked}; "
          f"{s.get('open_positions', 0)} open, {s.get('n', 0)} settled"
          + (f" (active only; {s['retired_excluded']} retired row(s) held out of "
             f"the headline: {held})" if s.get("retired_excluded") else ""))
    exp = s.get("exposure") or {}
    for reason, c in sorted((exp.get("by_reason") or {}).items()):
        print(f"  blocked: {c['distinct']} ticket(s) — {reason} "
              f"(seen {c['times']}x)")
    mk = s.get("maker") or {}
    if cfg.maker_first and (mk.get("pending") or mk.get("filled")
                            or mk.get("expired") or mk.get("fallback")):
        rate = mk.get("fill_rate")
        print(f"  maker: {mk.get('pending', 0)} pending "
              f"(+{filled} filled / +{expired} expired this run); "
              f"lifetime {mk.get('filled', 0)} filled, {mk.get('expired', 0)} expired"
              + (f", fill rate {rate:.0%}" if rate is not None else "")
              + (f", avg {mk['avg_fill_polls']} polls to fill"
                 if mk.get("avg_fill_polls") is not None else ""))
    if s.get("n"):
        print(f"  win rate {s['win_rate']:.1%} vs avg entry price "
              f"{s['avg_predicted']:.1%}  (edge {-s['calibration_gap']:+.1%} pts)")
        print(f"  ROI on stake {s['roi_on_stake']:+.2%}  "
              f"mean return {s['mean_return']:+.4f}  deploy={s['deploy']}")
        if s.get("reasons"):
            print("  not deployable: " + "; ".join(s["reasons"]))
    for src, sliced in sorted((s.get("by_source") or {}).items()):
        print(f"  [{src}] {sliced.get('n', 0)} settled, "
              f"{sliced.get('open_positions', 0)} open"
              + (f", win rate {sliced['win_rate']:.1%}" if sliced.get("n") else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
