"""A paper trial that settles itself, so "is the edge real" stops being a guess.

`backtest.py` has always been ready to answer that question and has never had an input
file. The Kalshi half of that is now fixed (`settle.py`), but the only healthy flow this
project has is the whale board - and board tickets are Polymarket markets, which
`settle.py` does not and should not know about. This module is the missing half: it
takes each published ticket, holds it, and labels it when the market resolves.

WHY IT LIVES IN ``docs/``: the board is regenerated by a GitHub Action on a fresh
checkout every ~15 minutes, and `.gitignore` excludes `data/` and `*.jsonl`, so a trial
kept there would be erased on every run. Writing to `docs/trial.json` - which the
workflow already commits - means the trial accrues automatically from a job that
already exists, and every position lands in the public commit log at the moment it was
opened. That last part is the real prize: the standard objection to a paper record is
that it could have been written after the fact, and a git history on a public repo is
the cheapest possible answer to it.

DELIBERATELY FLAT STAKES. Tickets are recorded at a fixed notional rather than at the
board's conviction-weighted size, because those are two different hypotheses - "the
signal picks winners" and "the conviction score sizes them well" - and you cannot test
two hypotheses with zero data. Test the signal first; conviction is recorded on every
row so it can be sliced later, once there is something to slice.

``pred`` IS THE ENTRY PRICE, not a forecast of our own. The board is a copy-trade
signal: it claims a position is worth taking, never that P(win) is some number. So the
honest null is the market's own price, which makes `backtest`'s ``calibration_gap``
(avg_pred - win_rate) read directly as realised edge in probability points, with a
NEGATIVE gap meaning the tickets beat the price they were bought at.

MAKER-FIRST ENTRIES (``Config.maker_first``). Kalshi charges resting orders nothing
on standard markets while the taker fee peaks at 1.75c/contract - on a 1-3c gross
edge that is the biggest single EV lever the system has, so the trial simulates it
rather than assume it. A ticket that carries a ``bid`` becomes a PENDING order at
that bid instead of an instant taker fill at the ask; on each later poll it fills
only if the market's ask has come to the limit, and after ``maker_max_polls`` it
cancels into an expired-intent log (or, opt-in, crosses at the then-current ask at
taker fees). The log keeps fair value and edge AS OF INTENT TIME, because scoring
fills alone drops the unfilled winners and keeps the filled losers - adverse
selection dressed up as edge. Tickets without a bid (whale, probe, bridge) keep
their existing accounting untouched.
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

from .fees import is_designated, maker_trade_fee, trade_fee

# A resolved Polymarket market pays its winning leg at 1 and the rest at 0. Demanding
# the extremes - rather than trusting `closed` alone - is what keeps a UMA dispute or a
# mid-resolution read from being labelled as a settled bet. Anything in between stays
# open and is retried next run; an unsettleable position must never become a data point.
WON_AT = 0.99
LOST_AT = 0.01

DEFAULT_STAKE = 100.0

# The model sleeves' own inputs, carried verbatim onto the row when the ticket has
# them. Without these the trial can prove a sleeve wins or loses but never WHY -
# `model_prob` against `won` is the calibration check each sleeve exists to earn, and
# a trial that drops it can validate the picks while leaving the model unfalsifiable.
# Weather fields (`*_f`), gas fields (aaa_*, drift, sigma, forecast, lr_tilt,
# market_mu, market_sigma) and spxindex fields (spot_used, chain_ts, vrp_shrink,
# fair, implied_sigma, series) never collide, so one spread list serves all: rows
# only pick up keys the ticket carries.
MODEL_FIELDS = ("model_prob", "edge", "forecast_f", "sigma_f", "market_mu_f",
                "market_sigma_f", "days_ahead", "market_prob", "model", "city",
                "forecast_src", "nbm_cycle", "nbm_sd_f", "forecast_grid_f",
                # Calibration-overlay verdict (calibration.py): the corrected market
                # probability, the edge against it, and the slope used. Carried so the
                # veto rule itself can be scored once rows settle.
                "cal_prob", "cal_edge", "cal_b",
                # Sports de-vig A/B: fair value under every method plus which one
                # was operative, so the trial can score multiplicative vs power vs
                # Shin from ONE run instead of needing a trial per method.
                "fair_mult", "fair_power", "fair_shin", "devig_method",
                "aaa_today", "aaa_target_date", "drift", "sigma", "forecast",
                "lr_tilt", "market_mu", "market_sigma",
                "spot_used", "chain_ts", "vrp_shrink", "fair", "implied_sigma",
                "series")


def venue_of(row: dict) -> str:
    """Which exchange a position lives on, inferred when the row predates the field.

    Rows written before Kalshi existed in the trial carry no ``venue``, and there are
    live ones in `docs/trial.json` - so this must keep working rather than relabel
    history. The id shape is unambiguous: Polymarket keys are `0x` + 64 hex, Kalshi
    tickers are uppercase series-and-strike. Defaulting to polymarket also means a
    corrupt or empty id keeps its old behaviour instead of being routed somewhere new.
    """
    v = (row.get("venue") or "").strip().lower()
    if v:
        return v
    mid = (row.get("market_id") or "").strip()
    # Note the shape of the test: an id must be PRESENT and non-Polymarket to route to
    # Kalshi. Asking only "does it lack an 0x prefix" sends an empty or corrupt id to
    # the new venue, which is the one case that should keep its old behaviour.
    return "kalshi" if mid and not mid.startswith("0x") else "polymarket"


def _key(market_id: str, outcome: str) -> str:
    """One position per market leg, ever. First sighting wins.

    The board republishes the same ticket every cycle for as long as it qualifies, so
    without this the trial would record the same opinion dozens of times, inflate `n`
    with copies of one bet, and let a later, better price silently replace the one we
    would actually have paid.
    """
    return f"{market_id}:{outcome.strip().lower()}"


def load(path: str | Path) -> dict:
    p = Path(path)
    if not p.exists():
        return {"open": [], "settled": [], "stats": {}}
    data = json.loads(p.read_text(encoding="utf-8"))
    data.setdefault("open", [])
    data.setdefault("settled", [])
    data.setdefault("voided", [])
    data.setdefault("pending", [])
    data.setdefault("stats", {})
    return data


def save(path: str | Path, trial: dict) -> None:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(trial, indent=2), encoding="utf-8")


def record(trial: dict, tickets: list[dict], *, stake: float = DEFAULT_STAKE,
           fee_multiplier: float = 0.07, maker: bool = True,
           maker_first: bool = False, now: float | None = None) -> int:
    """Open a paper position (or a pending maker order) for each ticket not
    already held. Returns how many were newly recorded, intents included."""
    now = time.time() if now is None else now
    pending = trial.setdefault("pending", [])
    expired = (trial.get("maker") or {}).get("expired") or []
    # Pending and expired intents both block re-entry. Pending for the same reason
    # open rows do; expired because "retry until it fills" is exactly the adverse-
    # selection machine this module exists to expose - keep placing the order and
    # the record fills only when the market comes down through it.
    seen = {r["key"] for r in trial["open"]} | {r["key"] for r in trial["settled"]} \
        | {r["key"] for r in pending} | {r["key"] for r in expired}
    added = 0
    for t in tickets:
        price = float(t.get("entry_price") or 0.0)
        if not 0.0 < price < 1.0:
            continue                       # unpriceable: not a position, not a data point
        key = _key(t.get("market_id", ""), t.get("outcome", ""))
        if key in seen:
            continue
        base = {
            "key": key,
            "market_id": t.get("market_id", ""),
            "venue": venue_of(t),
            "outcome": t.get("outcome", ""),
            "title": t.get("title", ""),
            "url": t.get("url", ""),
            "stake": round(stake, 4),
            # Everything below is for slicing the result later, not for scoring it.
            # True = cleared the buy bar and was recommended. False = cleared every hard
            # filter but sat below it. Only the first is evidence about the board as
            # published; both are evidence about where the bar belongs.
            "shown": bool(t.get("_shown", True)),
            # Which hypothesis this row is evidence FOR. The trial now carries two
            # sleeves that share a settlement path and share nothing else, so a pooled
            # win rate would answer neither question - see `stats`.
            "source": t.get("source") or "whale",
            "conviction": t.get("conviction"),
            "n_wallets": t.get("n_wallets"),
            "whale_usd": t.get("whale_usd"),
            "drift_c": t.get("drift_c"),
            "hours_to_resolve": t.get("hours_to_resolve"),
            "liquidity": t.get("liquidity"),
            "end_iso": t.get("end_iso", ""),
            "event_iso": t.get("event_iso", ""),
            **{k: t[k] for k in MODEL_FIELDS if k in t},
            # Bridge rows resolve via the market they were copied FROM (see `main`):
            # a PM-US slug can't be asked Gamma anything, but its origin can.
            "origin_market_id": t.get("origin_market_id", ""),
        }
        bid = float(t.get("bid") or 0.0)
        if maker_first and 0.0 < bid < price:
            # Maker-first: join the bid instead of crossing to the ask, and record
            # the case for the trade AT INTENT TIME. If this order never fills, the
            # intent - fair value, edge, foregone price - is what the trial keeps,
            # because a record of fills alone drops the unfilled winners and keeps
            # the filled losers, which manufactures edge out of adverse selection.
            pending.append({
                **base,
                "intent_at": now,
                "limit_price": round(bid, 4),
                "intended_price": round(bid, 4),
                "ask_at_intent": round(price, 4),
                "fair_at_intent": t.get("model_prob"),
                "edge_at_intent": t.get("edge"),
                "polls": 0,
            })
        else:
            contracts = stake / price
            base.update({
                "opened_at": now,
                "price": round(price, 4),
                "contracts": round(contracts, 4),
                # `_maker` and `_fee_mult` are per-ticket overrides of the trial-wide
                # defaults. Bridge rows model taking the ask the moment the board
                # fires, and a taker fill booked at maker fees would understate the
                # venue cost the sleeve exists to measure. `_fee_mult` exists because
                # Kalshi does not charge one multiplier: S&P/Nasdaq markets are 0.035
                # where the general schedule is 0.07, and booking an index row at the
                # general rate would double its modelled cost.
                "fee": trade_fee(price, max(1, round(contracts)),
                                 multiplier=float(t.get("_fee_mult") or fee_multiplier),
                                 maker=bool(t.get("_maker", maker))),
            })
            trial["open"].append(base)
        seen.add(key)
        added += 1
    return added


def _open_from_pending(trial: dict, row: dict, *, price: float, now: float,
                       taker: bool, fee_multiplier: float) -> None:
    """Turn a pending maker order into an open row at ``price``."""
    contracts = row["stake"] / price
    if taker:
        fee = trade_fee(price, max(1, round(contracts)),
                        multiplier=fee_multiplier, maker=False)
    else:
        # Maker fills are free on standard markets; `is_designated` is the hook
        # for the few series Kalshi charges 25% of taker on resting orders.
        fee = maker_trade_fee(price, max(1, round(contracts)),
                              multiplier=fee_multiplier,
                              designated=is_designated(row["market_id"]))
    open_row = {k: v for k, v in row.items() if k != "polls"}
    open_row.update({
        "opened_at": now,
        "price": round(price, 4),
        "contracts": round(contracts, 4),
        "filled_price": round(price, 4),
        "fill_polls": row["polls"],
        "maker": not taker,
        "fee": fee,
    })
    if taker:
        open_row["maker_fallback"] = True
    trial["open"].append(open_row)


def check_fills(trial: dict, quotes: dict[str, dict], *, max_polls: int = 8,
                fallback_taker: bool = False, fee_multiplier: float = 0.07,
                now: float | None = None) -> tuple[int, int]:
    """Advance every pending maker order one poll. Returns (filled, expired).

    The fill rule is deliberately conservative: a resting bid fills ONLY when a
    later snapshot shows the ask at or through our limit - the market came to us.
    Touches, queue position, and trades inside the spread are all invisible to a
    15-minute poller, and guessing about them would flatter the fill rate on
    exactly the orders adverse selection punishes.

    An order still unfilled after ``max_polls`` either cancels (default) - moving
    to the expired-intent log with its edge-at-intent so unfilled winners cannot
    silently vanish from the record - or, with ``fallback_taker``, crosses the
    spread at the then-current ask at taker fees. A fallback with no live quote
    cancels instead: inventing a price to cross at would be fiction.
    """
    now = time.time() if now is None else now
    still: list[dict] = []
    filled = expired = 0
    for row in trial.setdefault("pending", []):
        row["polls"] = int(row.get("polls") or 0) + 1
        q = quotes.get(row["key"]) or {}
        ask = float(q.get("ask") or 0.0)
        if 0.0 < ask < 1.0 and ask <= row["limit_price"] + 1e-9:
            _open_from_pending(trial, row, price=row["limit_price"], now=now,
                               taker=False, fee_multiplier=fee_multiplier)
            filled += 1
        elif row["polls"] >= max_polls:
            if fallback_taker and 0.0 < ask < 1.0:
                _open_from_pending(trial, row, price=ask, now=now,
                                   taker=True, fee_multiplier=fee_multiplier)
                filled += 1
            else:
                mk = trial.setdefault("maker", {})
                mk.setdefault("expired", []).append({**row, "expired_at": now})
                expired += 1
        else:
            still.append(row)
    trial["pending"] = still
    return filled, expired


def retag_weather_fees(trial: dict, *, multiplier: float = 0.07) -> int:
    """Recharge still-open weather rows at taker fees. Returns how many changed.

    A weather entry takes the ask the moment the model fires - a taker cross by
    construction - but the sleeve's first weeks of rows were booked at the trial-wide
    maker default, 25% of the taker fee. On an 8c bracket that understates cost by
    ~$4.83 per $100 stake, which is ~5 points of phantom edge on the one sleeve that
    is actually Kalshi-tradeable; left alone, the DSR gate would be judging fiction.
    Open rows are positions, not results, so recomputing their fee is a correction
    rather than a rewrite - and settled rows are never touched, both because none
    settled before the fix and because editing settled evidence would be worse than
    the bug. Idempotent: a row already at taker fees recomputes to itself.
    """
    changed = 0
    for row in trial["open"]:
        if source_of(row) != "weather":
            continue
        # Maker-first fills are not taker crosses: their fee was set at fill time
        # by `check_fills` and recharging them here would undo the very accounting
        # the maker-first path exists to record.
        if "fill_polls" in row:
            continue
        fee = trade_fee(row["price"], max(1, round(row["contracts"])),
                        multiplier=multiplier, maker=False)
        if fee != row.get("fee"):
            row["fee"] = fee
            changed += 1
    return changed


def _winner(meta: dict) -> str | None:
    """Name of the winning outcome, or None if this market has not cleanly resolved."""
    if not meta.get("closed"):
        return None
    names = meta.get("outcomes") or []
    prices = meta.get("prices") or []
    if len(names) != len(prices) or not names:
        return None
    winners = [n for n, p in zip(names, prices) if p >= WON_AT]
    losers = [n for n, p in zip(names, prices) if p <= LOST_AT]
    # Exactly one leg at 1 and every other at 0. A market that is closed but still
    # quoting anything in between is mid-resolution or disputed, and saying so is the
    # whole point - a paper record that guesses is worth less than no paper record.
    if len(winners) == 1 and len(losers) == len(names) - 1:
        return winners[0]
    return None


def settle(trial: dict, metas: dict[str, dict], *, now: float | None = None) -> int:
    """Label every open position whose market has resolved. Returns how many."""
    now = time.time() if now is None else now
    still_open, settled = [], 0
    for row in trial["open"]:
        meta = metas.get(row["market_id"]) or {}
        # A voided market never resolves. Holding it would leave a position open
        # forever, quietly inflating the open count with something that can never
        # become evidence - so it leaves the trial and is recorded as withdrawn
        # rather than deleted, because a vanishing row looks like a hidden loss.
        if meta.get("voided"):
            trial.setdefault("voided", []).append({**row, "voided_at": now})
            continue
        winner = _winner(meta)
        if winner is None:
            still_open.append(row)
            continue
        won = winner.strip().lower() == row["outcome"].strip().lower()
        price, contracts, stake, fee = (
            row["price"], row["contracts"], row["stake"], row["fee"])
        realized = (contracts * (1.0 - price) - fee) if won else (-stake - fee)
        trial["settled"].append({
            **row,
            "settled_at": now,
            "winner": winner,
            "won": won,
            # The market's own price at entry. See the module docstring: this makes
            # `calibration_gap` read as realised edge, with negative meaning we beat it.
            "pred": price,
            "realized": round(realized, 4),
        })
        settled += 1
    trial["open"] = still_open
    return settled


def source_of(row: dict) -> str:
    """Which sleeve a row belongs to, inferred when the row predates the field."""
    return (row.get("source") or "").strip().lower() or "whale"


# Sleeves that have been switched off after being scored. Their rows STAY in the file -
# a track record that deletes its losers is worth nothing, and in a public git repo the
# deletion would not even hide them, it would just publish a diff of losing rows being
# removed. They are excluded from the HEADLINE instead, because the headline's job is to
# answer "how does the bot that runs tomorrow perform", and no sleeve that is switched
# off runs tomorrow. The pooled all-time number is kept alongside, under
# `including_retired`, so nothing is quietly lost. Retiring a sleeve is therefore an
# append to this set plus a config flag - never an edit to the settled rows.
RETIRED_SOURCES = frozenset({"weather"})


def stats(trial: dict, *, min_n: int = 30) -> dict:
    """Score the settled rows with the project's existing gate, plus trial bookkeeping.

    The headline covers the ACTIVE sleeves only (see `RETIRED_SOURCES`); the all-time
    pooled figure lives in `including_retired`. `by_source` is still where any decision
    belongs, and it reports every sleeve including the retired ones. The sleeves make
    different claims on different markets with different holding periods; a pooled win
    rate that mixes a six-month Polymarket resolution with a next-day Kalshi temperature
    is arithmetic, not evidence. Whichever sleeve reaches `min_n` first gets judged first.
    """
    from .backtest import evaluate

    live = [r for r in trial["settled"] if source_of(r) not in RETIRED_SOURCES]
    live_open = [r for r in trial["open"] if source_of(r) not in RETIRED_SOURCES]

    out = evaluate(live, min_n=min_n)
    out["open_positions"] = len(live_open)
    out["retired_sources"] = sorted(RETIRED_SOURCES)
    out["retired_excluded"] = len(trial["settled"]) - len(live)
    # The all-time record, pooled across every sleeve that ever ran. Reported rather
    # than discarded: the headline answers "what runs tomorrow", this answers "what did
    # this project actually do", and the gap between them is itself the audit trail.
    if len(live) != len(trial["settled"]):
        out["including_retired"] = evaluate(trial["settled"], min_n=min_n)
    if trial["settled"]:
        span = max(r["settled_at"] for r in trial["settled"]) - \
            min(r["opened_at"] for r in trial["settled"])
        out["trial_days"] = round(span / 86400.0, 1)

    sleeves: dict[str, list[dict]] = {}
    for row in trial["settled"]:
        sleeves.setdefault(source_of(row), []).append(row)
    open_by: dict[str, int] = {}
    for row in trial["open"]:
        src = source_of(row)
        open_by[src] = open_by.get(src, 0) + 1
    out["by_source"] = {}
    for src in sorted(set(sleeves) | set(open_by)):
        sliced = evaluate(sleeves.get(src, []), min_n=min_n)
        sliced["open_positions"] = open_by.get(src, 0)
        # Flagged, not dropped. A reader who only ever sees the headline should still
        # be able to find the sleeve that was switched off, and why the two top-line
        # numbers differ.
        if src in RETIRED_SOURCES:
            sliced["retired"] = True
        out["by_source"][src] = sliced
    out["maker"] = maker_stats(trial)
    return out


def maker_stats(trial: dict) -> dict:
    """The maker-first simulation's own scoreboard, fills and non-fills alike.

    The number that matters most here is the pairing of `fill_rate` with
    `foregone_edge`: a high fill rate with low foregone edge says passive entry
    is nearly free; a low fill rate with high foregone edge says the maker
    saving is being paid for in missed trades, which no per-fill fee number
    would ever reveal on its own.
    """
    rows = trial["open"] + trial["settled"] + (trial.get("voided") or [])
    fills = [r for r in rows if r.get("maker") and "fill_polls" in r]
    fallbacks = [r for r in rows if r.get("maker_fallback")]
    expired = (trial.get("maker") or {}).get("expired") or []
    resolved = len(fills) + len(fallbacks) + len(expired)
    return {
        "pending": len(trial.get("pending") or []),
        "filled": len(fills),
        "fallback": len(fallbacks),
        "expired": len(expired),
        "fill_rate": round(len(fills) / resolved, 4) if resolved else None,
        "avg_fill_polls": round(sum(r["fill_polls"] for r in fills) / len(fills), 2)
        if fills else None,
        # Edge the record walked away from by not chasing: the sum of edge-at-
        # intent over every cancelled order. Read it against the fee savings.
        "foregone_edge": round(sum(float(r.get("edge_at_intent") or 0.0)
                                   for r in expired), 4),
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="predictionedge.papertrial")
    ap.add_argument("--board", default="docs/board.json")
    ap.add_argument("--trial", default="docs/trial.json")
    ap.add_argument("--stake", type=float, default=DEFAULT_STAKE)
    ap.add_argument("--no-settle", action="store_true",
                    help="record new tickets but skip the settlement fetch")
    args = ap.parse_args(argv)

    from .config import Config
    cfg = Config.from_env()
    trial = load(args.trial)
    repriced = retag_weather_fees(trial, multiplier=cfg.fee_multiplier)
    if repriced:
        print(f"repriced {repriced} open weather row(s) at taker fees")

    board = json.loads(Path(args.board).read_text(encoding="utf-8"))
    # Stamp positions with when the board SAW that price, not when this process ran.
    # They differ whenever a scheduled run is skipped or the board is replayed, and the
    # hold time is what the whole trial measures - dating an entry to the replay would
    # quietly shorten every holding period in the record.
    # `probe` sits below the buy bar. Recording it is the whole point: a threshold can
    # only be validated against outcomes on BOTH sides of it. Observe above the cutoff
    # alone and 0.45 stays unfalsifiable forever, however much data accumulates.
    # The weather sleeve arrives already filtered to what cleared its own edge bar, so
    # every row is `_shown`; it has no probe tier because its bar is a modelled edge
    # rather than a hand-set conviction cutoff that needs validating from both sides.
    # Weather rows also override the trial-wide maker default: their entry IS the ask,
    # so the honest fee is the taker fee - see `retag_weather_fees`.
    # Gas rows enter exactly as weather rows do: already filtered to what cleared
    # their own modelled edge bar (so every row is `_shown`), and their entry IS the
    # ask, so the honest fee is the taker fee.
    # The spxindex sleeve is a taker cross at the ask too, and its markets sit on
    # Kalshi's 0.035 index fee schedule - see `record` on `_fee_mult`.
    from .fees import INDEX_FEE_MULTIPLIER
    flow = [{**t, "_shown": True} for t in (board.get("tickets") or [])] + \
           [{**t, "_shown": False} for t in (board.get("probe") or [])] + \
           [{**t, "_shown": True, "_maker": False} for t in (board.get("weather") or [])] + \
           [{**t, "_shown": True, "_maker": False} for t in (board.get("gas") or [])] + \
           [{**t, "_shown": True, "_maker": False, "_fee_mult": INDEX_FEE_MULTIPLIER}
            for t in (board.get("spxindex") or [])]

    # Maker-first: this run's board IS the next 15-minute snapshot of every market a
    # pending order is resting in, so pending orders are checked against it BEFORE new
    # tickets are recorded - a fill can only come from a strictly later poll than the
    # intent. A market that dropped off the board contributes no quote, which reads as
    # "did not come to us" and counts the poll toward expiry; conservative on purpose.
    filled = expired = 0
    if cfg.maker_first:
        quotes = {_key(t.get("market_id", ""), t.get("outcome", "")):
                  {"bid": t.get("bid"), "ask": float(t.get("entry_price") or 0.0)}
                  for t in flow}
        filled, expired = check_fills(
            trial, quotes, max_polls=cfg.maker_max_polls,
            fallback_taker=cfg.maker_fallback_taker,
            fee_multiplier=cfg.fee_multiplier,
            now=board.get("generated_at") or None)

    added = record(trial, flow, stake=args.stake,
                   fee_multiplier=cfg.fee_multiplier, maker=cfg.assume_maker,
                   maker_first=cfg.maker_first,
                   now=board.get("generated_at") or None)

    # The venue bridge: every SHOWN whale ticket is re-recorded at the live ask on
    # the venues a US person can actually trade. Probe and weather rows are excluded -
    # probe is below the buy bar, and weather is already a Kalshi position. The whole
    # sleeve reads public quote endpoints only; a network failure here costs coverage
    # (and is logged as such), never correctness.
    if cfg.bridge_enabled and board.get("tickets"):
        from . import bridge as _bridge
        from .kalshi import _default_fetch as _kx_fetch
        from .polymarket_us import PolymarketUSClient
        b_tickets, attempts = _bridge.build_bridge_tickets(
            board["tickets"],
            pmus_client=PolymarketUSClient(),
            kalshi_fetch=_kx_fetch,
            series_map=_bridge.parse_series_env(cfg.bridge_kalshi_series),
            skip=_bridge.permanent_skips(trial))
        added += record(trial, b_tickets, stake=args.stake,
                        fee_multiplier=cfg.fee_multiplier, maker=cfg.assume_maker,
                        now=board.get("generated_at") or None)
        _bridge.update_log(trial, attempts,
                           now=board.get("generated_at") or time.time())

    settled = 0
    if not args.no_settle and trial["open"]:
        # Only open positions need a lookup, and they are the markets that have
        # dropped OFF the board - a resolved market is exactly the one the board
        # stopped showing, so this cannot be answered from board.json.
        #
        # Routed by venue because the two exchanges answer different questions with
        # different keys. Sending a Kalshi ticker to Gamma does not error, it returns
        # NOTHING - which reads as "not resolved yet" and would park every Kalshi row
        # open forever. Merging into one dict is safe: a Polymarket key is `0x`+64 hex
        # and a Kalshi ticker is not, so the two id spaces cannot collide.
        ids: dict[str, list[str]] = {}
        for r in trial["open"]:
            ids.setdefault(venue_of(r), []).append(r["market_id"])
        metas: dict[str, dict] = {}
        if ids.get("polymarket"):
            from .gamma import market_meta as pm_meta
            metas.update(pm_meta(ids["polymarket"]))
        if ids.get("kalshi"):
            from .kalshi import market_meta as kx_meta
            metas.update(kx_meta(ids["kalshi"]))
        # Bridge rows on PM-US settle by their ORIGIN market: PM-US has no public
        # resolution endpoint here, but the row is by construction the same contract
        # as the intl market it was copied from, so Gamma's answer for the origin IS
        # the answer - keyed back under the PM-US row's own market_id.
        pmus_rows = [r for r in trial["open"]
                     if venue_of(r) == "polymarket-us" and r.get("origin_market_id")]
        if pmus_rows:
            from .gamma import market_meta as pm_meta
            origin = pm_meta(sorted({r["origin_market_id"] for r in pmus_rows}))
            for r in pmus_rows:
                meta = origin.get(r["origin_market_id"])
                if meta:
                    metas[r["market_id"]] = meta
        settled = settle(trial, metas)

    trial["stats"] = stats(trial)
    trial["generated"] = time.strftime("%Y-%m-%d %H:%M:%S")
    save(args.trial, trial)

    s = trial["stats"]
    print(f"recorded {added} new, settled {settled}; "
          f"{s.get('open_positions', 0)} open, {s.get('n', 0)} settled"
          + (f" (active sleeves; {s['retired_excluded']} retired row(s) held out "
             f"of the headline)" if s.get("retired_excluded") else ""))
    mk = s.get("maker") or {}
    if cfg.maker_first and (mk.get("pending") or mk.get("filled")
                            or mk.get("expired") or mk.get("fallback")):
        rate = mk.get("fill_rate")
        print(f"  maker: {mk.get('pending', 0)} pending "
              f"(+{filled} filled / +{expired} expired this run); "
              f"lifetime {mk.get('filled', 0)} filled, {mk.get('expired', 0)} expired"
              + (f", fill rate {rate:.0%}" if rate is not None else "")
              + (f", avg {mk['avg_fill_polls']} polls to fill"
                 if mk.get("avg_fill_polls") is not None else ""))
    if s.get("n"):
        print(f"  win rate {s['win_rate']:.1%} vs avg entry price "
              f"{s['avg_predicted']:.1%}  (edge {-s['calibration_gap']:+.1%} pts)")
        print(f"  ROI on stake {s['roi_on_stake']:+.2%}  "
              f"mean return {s['mean_return']:+.4f}  deploy={s['deploy']}")
        if s.get("reasons"):
            print("  not deployable: " + "; ".join(s["reasons"]))
    for src, sliced in sorted((s.get("by_source") or {}).items()):
        print(f"  [{src}] {sliced.get('n', 0)} settled, "
              f"{sliced.get('open_positions', 0)} open"
              + (f", win rate {sliced['win_rate']:.1%}" if sliced.get("n") else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
