"""A paper trial that settles itself, so "is the edge real" stops being a guess.

`backtest.py` has always been ready to answer that question and has never had an input
file. The Kalshi half of that is now fixed (`settle.py`), but the only healthy flow this
project has is the whale board - and board tickets are Polymarket markets, which
`settle.py` does not and should not know about. This module is the missing half: it
takes each published ticket, holds it, and labels it when the market resolves.

WHY IT LIVES IN ``docs/``: the board is regenerated by a GitHub Action on a fresh
checkout every ~15 minutes, and `.gitignore` excludes `data/` and `*.jsonl`, so a trial
kept there would be erased on every run. Writing to `docs/trial.json` - which the
workflow already commits - means the trial accrues automatically from a job that
already exists, and every position lands in the public commit log at the moment it was
opened. That last part is the real prize: the standard objection to a paper record is
that it could have been written after the fact, and a git history on a public repo is
the cheapest possible answer to it.

DELIBERATELY FLAT STAKES. Tickets are recorded at a fixed notional rather than at the
board's conviction-weighted size, because those are two different hypotheses - "the
signal picks winners" and "the conviction score sizes them well" - and you cannot test
two hypotheses with zero data. Test the signal first; conviction is recorded on every
row so it can be sliced later, once there is something to slice.

``pred`` IS THE ENTRY PRICE, not a forecast of our own. The board is a copy-trade
signal: it claims a position is worth taking, never that P(win) is some number. So the
honest null is the market's own price, which makes `backtest`'s ``calibration_gap``
(avg_pred - win_rate) read directly as realised edge in probability points, with a
NEGATIVE gap meaning the tickets beat the price they were bought at.
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

from .fees import trade_fee

# A resolved Polymarket market pays its winning leg at 1 and the rest at 0. Demanding
# the extremes - rather than trusting `closed` alone - is what keeps a UMA dispute or a
# mid-resolution read from being labelled as a settled bet. Anything in between stays
# open and is retried next run; an unsettleable position must never become a data point.
WON_AT = 0.99
LOST_AT = 0.01

DEFAULT_STAKE = 100.0

# The model sleeves' own inputs, carried verbatim onto the row when the ticket has
# them. Without these the trial can prove a sleeve wins or loses but never WHY -
# `model_prob` against `won` is the calibration check each sleeve exists to earn, and
# a trial that drops it can validate the picks while leaving the model unfalsifiable.
# Weather fields (`*_f`) and gas fields (aaa_*, drift, sigma, forecast, lr_tilt,
# market_mu, market_sigma) never collide, so one spread list serves both.
MODEL_FIELDS = ("model_prob", "edge", "forecast_f", "sigma_f", "market_mu_f",
                "market_sigma_f", "days_ahead", "market_prob", "model", "city",
                "forecast_src", "nbm_cycle", "nbm_sd_f", "forecast_grid_f",
                "aaa_today", "aaa_target_date", "drift", "sigma", "forecast",
                "lr_tilt", "market_mu", "market_sigma")


def venue_of(row: dict) -> str:
    """Which exchange a position lives on, inferred when the row predates the field.

    Rows written before Kalshi existed in the trial carry no ``venue``, and there are
    live ones in `docs/trial.json` - so this must keep working rather than relabel
    history. The id shape is unambiguous: Polymarket keys are `0x` + 64 hex, Kalshi
    tickers are uppercase series-and-strike. Defaulting to polymarket also means a
    corrupt or empty id keeps its old behaviour instead of being routed somewhere new.
    """
    v = (row.get("venue") or "").strip().lower()
    if v:
        return v
    mid = (row.get("market_id") or "").strip()
    # Note the shape of the test: an id must be PRESENT and non-Polymarket to route to
    # Kalshi. Asking only "does it lack an 0x prefix" sends an empty or corrupt id to
    # the new venue, which is the one case that should keep its old behaviour.
    return "kalshi" if mid and not mid.startswith("0x") else "polymarket"


def _key(market_id: str, outcome: str) -> str:
    """One position per market leg, ever. First sighting wins.

    The board republishes the same ticket every cycle for as long as it qualifies, so
    without this the trial would record the same opinion dozens of times, inflate `n`
    with copies of one bet, and let a later, better price silently replace the one we
    would actually have paid.
    """
    return f"{market_id}:{outcome.strip().lower()}"


def load(path: str | Path) -> dict:
    p = Path(path)
    if not p.exists():
        return {"open": [], "settled": [], "stats": {}}
    data = json.loads(p.read_text(encoding="utf-8"))
    data.setdefault("open", [])
    data.setdefault("settled", [])
    data.setdefault("voided", [])
    data.setdefault("stats", {})
    return data


def save(path: str | Path, trial: dict) -> None:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(trial, indent=2), encoding="utf-8")


def record(trial: dict, tickets: list[dict], *, stake: float = DEFAULT_STAKE,
           fee_multiplier: float = 0.07, maker: bool = True,
           now: float | None = None) -> int:
    """Open a paper position for each ticket not already held. Returns how many."""
    now = time.time() if now is None else now
    seen = {r["key"] for r in trial["open"]} | {r["key"] for r in trial["settled"]}
    added = 0
    for t in tickets:
        price = float(t.get("entry_price") or 0.0)
        if not 0.0 < price < 1.0:
            continue                       # unpriceable: not a position, not a data point
        key = _key(t.get("market_id", ""), t.get("outcome", ""))
        if key in seen:
            continue
        contracts = stake / price
        trial["open"].append({
            "key": key,
            "opened_at": now,
            "market_id": t.get("market_id", ""),
            "venue": venue_of(t),
            "outcome": t.get("outcome", ""),
            "title": t.get("title", ""),
            "url": t.get("url", ""),
            "price": round(price, 4),
            "stake": round(stake, 4),
            "contracts": round(contracts, 4),
            # Everything below is for slicing the result later, not for scoring it.
            # True = cleared the buy bar and was recommended. False = cleared every hard
            # filter but sat below it. Only the first is evidence about the board as
            # published; both are evidence about where the bar belongs.
            "shown": bool(t.get("_shown", True)),
            # Which hypothesis this row is evidence FOR. The trial now carries two
            # sleeves that share a settlement path and share nothing else, so a pooled
            # win rate would answer neither question - see `stats`.
            "source": t.get("source") or "whale",
            "conviction": t.get("conviction"),
            "n_wallets": t.get("n_wallets"),
            "whale_usd": t.get("whale_usd"),
            "drift_c": t.get("drift_c"),
            "hours_to_resolve": t.get("hours_to_resolve"),
            "liquidity": t.get("liquidity"),
            "end_iso": t.get("end_iso", ""),
            "event_iso": t.get("event_iso", ""),
            **{k: t[k] for k in MODEL_FIELDS if k in t},
            # Bridge rows resolve via the market they were copied FROM (see `main`):
            # a PM-US slug can't be asked Gamma anything, but its origin can.
            "origin_market_id": t.get("origin_market_id", ""),
            # `_maker` is a per-ticket override of the trial-wide default. Bridge rows
            # model taking the ask the moment the board fires, and a taker fill booked
            # at maker fees would understate the venue cost the sleeve exists to measure.
            "fee": trade_fee(price, max(1, round(contracts)),
                             multiplier=fee_multiplier,
                             maker=bool(t.get("_maker", maker))),
        })
        seen.add(key)
        added += 1
    return added


def retag_weather_fees(trial: dict, *, multiplier: float = 0.07) -> int:
    """Recharge still-open weather rows at taker fees. Returns how many changed.

    A weather entry takes the ask the moment the model fires - a taker cross by
    construction - but the sleeve's first weeks of rows were booked at the trial-wide
    maker default, 25% of the taker fee. On an 8c bracket that understates cost by
    ~$4.83 per $100 stake, which is ~5 points of phantom edge on the one sleeve that
    is actually Kalshi-tradeable; left alone, the DSR gate would be judging fiction.
    Open rows are positions, not results, so recomputing their fee is a correction
    rather than a rewrite - and settled rows are never touched, both because none
    settled before the fix and because editing settled evidence would be worse than
    the bug. Idempotent: a row already at taker fees recomputes to itself.
    """
    changed = 0
    for row in trial["open"]:
        if source_of(row) != "weather":
            continue
        fee = trade_fee(row["price"], max(1, round(row["contracts"])),
                        multiplier=multiplier, maker=False)
        if fee != row.get("fee"):
            row["fee"] = fee
            changed += 1
    return changed


def _winner(meta: dict) -> str | None:
    """Name of the winning outcome, or None if this market has not cleanly resolved."""
    if not meta.get("closed"):
        return None
    names = meta.get("outcomes") or []
    prices = meta.get("prices") or []
    if len(names) != len(prices) or not names:
        return None
    winners = [n for n, p in zip(names, prices) if p >= WON_AT]
    losers = [n for n, p in zip(names, prices) if p <= LOST_AT]
    # Exactly one leg at 1 and every other at 0. A market that is closed but still
    # quoting anything in between is mid-resolution or disputed, and saying so is the
    # whole point - a paper record that guesses is worth less than no paper record.
    if len(winners) == 1 and len(losers) == len(names) - 1:
        return winners[0]
    return None


def settle(trial: dict, metas: dict[str, dict], *, now: float | None = None) -> int:
    """Label every open position whose market has resolved. Returns how many."""
    now = time.time() if now is None else now
    still_open, settled = [], 0
    for row in trial["open"]:
        meta = metas.get(row["market_id"]) or {}
        # A voided market never resolves. Holding it would leave a position open
        # forever, quietly inflating the open count with something that can never
        # become evidence - so it leaves the trial and is recorded as withdrawn
        # rather than deleted, because a vanishing row looks like a hidden loss.
        if meta.get("voided"):
            trial.setdefault("voided", []).append({**row, "voided_at": now})
            continue
        winner = _winner(meta)
        if winner is None:
            still_open.append(row)
            continue
        won = winner.strip().lower() == row["outcome"].strip().lower()
        price, contracts, stake, fee = (
            row["price"], row["contracts"], row["stake"], row["fee"])
        realized = (contracts * (1.0 - price) - fee) if won else (-stake - fee)
        trial["settled"].append({
            **row,
            "settled_at": now,
            "winner": winner,
            "won": won,
            # The market's own price at entry. See the module docstring: this makes
            # `calibration_gap` read as realised edge, with negative meaning we beat it.
            "pred": price,
            "realized": round(realized, 4),
        })
        settled += 1
    trial["open"] = still_open
    return settled


def source_of(row: dict) -> str:
    """Which sleeve a row belongs to, inferred when the row predates the field."""
    return (row.get("source") or "").strip().lower() or "whale"


def stats(trial: dict, *, min_n: int = 30) -> dict:
    """Score the settled rows with the project's existing gate, plus trial bookkeeping.

    The headline numbers stay pooled so the top-line record is one honest number, but
    `by_source` is where any decision belongs. The sleeves make different claims on
    different markets with different holding periods; a pooled win rate that mixes a
    six-month Polymarket resolution with a next-day Kalshi temperature is arithmetic,
    not evidence. Whichever sleeve reaches `min_n` first gets judged first.
    """
    from .backtest import evaluate

    out = evaluate(trial["settled"], min_n=min_n)
    out["open_positions"] = len(trial["open"])
    if trial["settled"]:
        span = max(r["settled_at"] for r in trial["settled"]) - \
            min(r["opened_at"] for r in trial["settled"])
        out["trial_days"] = round(span / 86400.0, 1)

    sleeves: dict[str, list[dict]] = {}
    for row in trial["settled"]:
        sleeves.setdefault(source_of(row), []).append(row)
    open_by: dict[str, int] = {}
    for row in trial["open"]:
        src = source_of(row)
        open_by[src] = open_by.get(src, 0) + 1
    out["by_source"] = {}
    for src in sorted(set(sleeves) | set(open_by)):
        sliced = evaluate(sleeves.get(src, []), min_n=min_n)
        sliced["open_positions"] = open_by.get(src, 0)
        out["by_source"][src] = sliced
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="predictionedge.papertrial")
    ap.add_argument("--board", default="docs/board.json")
    ap.add_argument("--trial", default="docs/trial.json")
    ap.add_argument("--stake", type=float, default=DEFAULT_STAKE)
    ap.add_argument("--no-settle", action="store_true",
                    help="record new tickets but skip the settlement fetch")
    args = ap.parse_args(argv)

    from .config import Config
    cfg = Config.from_env()
    trial = load(args.trial)
    repriced = retag_weather_fees(trial, multiplier=cfg.fee_multiplier)
    if repriced:
        print(f"repriced {repriced} open weather row(s) at taker fees")

    board = json.loads(Path(args.board).read_text(encoding="utf-8"))
    # Stamp positions with when the board SAW that price, not when this process ran.
    # They differ whenever a scheduled run is skipped or the board is replayed, and the
    # hold time is what the whole trial measures - dating an entry to the replay would
    # quietly shorten every holding period in the record.
    # `probe` sits below the buy bar. Recording it is the whole point: a threshold can
    # only be validated against outcomes on BOTH sides of it. Observe above the cutoff
    # alone and 0.45 stays unfalsifiable forever, however much data accumulates.
    # The weather sleeve arrives already filtered to what cleared its own edge bar, so
    # every row is `_shown`; it has no probe tier because its bar is a modelled edge
    # rather than a hand-set conviction cutoff that needs validating from both sides.
    # Weather rows also override the trial-wide maker default: their entry IS the ask,
    # so the honest fee is the taker fee - see `retag_weather_fees`.
    # Gas rows enter exactly as weather rows do: already filtered to what cleared
    # their own modelled edge bar (so every row is `_shown`), and their entry IS the
    # ask, so the honest fee is the taker fee.
    flow = [{**t, "_shown": True} for t in (board.get("tickets") or [])] + \
           [{**t, "_shown": False} for t in (board.get("probe") or [])] + \
           [{**t, "_shown": True, "_maker": False} for t in (board.get("weather") or [])] + \
           [{**t, "_shown": True, "_maker": False} for t in (board.get("gas") or [])]
    added = record(trial, flow, stake=args.stake,
                   fee_multiplier=cfg.fee_multiplier, maker=cfg.assume_maker,
                   now=board.get("generated_at") or None)

    # The venue bridge: every SHOWN whale ticket is re-recorded at the live ask on
    # the venues a US person can actually trade. Probe and weather rows are excluded -
    # probe is below the buy bar, and weather is already a Kalshi position. The whole
    # sleeve reads public quote endpoints only; a network failure here costs coverage
    # (and is logged as such), never correctness.
    if cfg.bridge_enabled and board.get("tickets"):
        from . import bridge as _bridge
        from .kalshi import _default_fetch as _kx_fetch
        from .polymarket_us import PolymarketUSClient
        b_tickets, attempts = _bridge.build_bridge_tickets(
            board["tickets"],
            pmus_client=PolymarketUSClient(),
            kalshi_fetch=_kx_fetch,
            series_map=_bridge.parse_series_env(cfg.bridge_kalshi_series),
            skip=_bridge.permanent_skips(trial))
        added += record(trial, b_tickets, stake=args.stake,
                        fee_multiplier=cfg.fee_multiplier, maker=cfg.assume_maker,
                        now=board.get("generated_at") or None)
        _bridge.update_log(trial, attempts,
                           now=board.get("generated_at") or time.time())

    settled = 0
    if not args.no_settle and trial["open"]:
        # Only open positions need a lookup, and they are the markets that have
        # dropped OFF the board - a resolved market is exactly the one the board
        # stopped showing, so this cannot be answered from board.json.
        #
        # Routed by venue because the two exchanges answer different questions with
        # different keys. Sending a Kalshi ticker to Gamma does not error, it returns
        # NOTHING - which reads as "not resolved yet" and would park every Kalshi row
        # open forever. Merging into one dict is safe: a Polymarket key is `0x`+64 hex
        # and a Kalshi ticker is not, so the two id spaces cannot collide.
        ids: dict[str, list[str]] = {}
        for r in trial["open"]:
            ids.setdefault(venue_of(r), []).append(r["market_id"])
        metas: dict[str, dict] = {}
        if ids.get("polymarket"):
            from .gamma import market_meta as pm_meta
            metas.update(pm_meta(ids["polymarket"]))
        if ids.get("kalshi"):
            from .kalshi import market_meta as kx_meta
            metas.update(kx_meta(ids["kalshi"]))
        # Bridge rows on PM-US settle by their ORIGIN market: PM-US has no public
        # resolution endpoint here, but the row is by construction the same contract
        # as the intl market it was copied from, so Gamma's answer for the origin IS
        # the answer - keyed back under the PM-US row's own market_id.
        pmus_rows = [r for r in trial["open"]
                     if venue_of(r) == "polymarket-us" and r.get("origin_market_id")]
        if pmus_rows:
            from .gamma import market_meta as pm_meta
            origin = pm_meta(sorted({r["origin_market_id"] for r in pmus_rows}))
            for r in pmus_rows:
                meta = origin.get(r["origin_market_id"])
                if meta:
                    metas[r["market_id"]] = meta
        settled = settle(trial, metas)

    trial["stats"] = stats(trial)
    trial["generated"] = time.strftime("%Y-%m-%d %H:%M:%S")
    save(args.trial, trial)

    s = trial["stats"]
    print(f"recorded {added} new, settled {settled}; "
          f"{s.get('open_positions', 0)} open, {s.get('n', 0)} settled")
    if s.get("n"):
        print(f"  win rate {s['win_rate']:.1%} vs avg entry price "
              f"{s['avg_predicted']:.1%}  (edge {-s['calibration_gap']:+.1%} pts)")
        print(f"  ROI on stake {s['roi_on_stake']:+.2%}  "
              f"mean return {s['mean_return']:+.4f}  deploy={s['deploy']}")
        if s.get("reasons"):
            print("  not deployable: " + "; ".join(s["reasons"]))
    for src, sliced in sorted((s.get("by_source") or {}).items()):
        print(f"  [{src}] {sliced.get('n', 0)} settled, "
              f"{sliced.get('open_positions', 0)} open"
              + (f", win rate {sliced['win_rate']:.1%}" if sliced.get("n") else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
